package codegen

var structTemplate = `type {{.StructName}} struct { {{range .Fields}}
{{.Description}}
	{{.Name}} {{.Type}} {{.Tag}}
{{end}}}`

var codeFileTemplate = `// This file is generated by tools, DO NOT EDIT.
package {{.PackageName}}

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/cloudcarver/anchor/internal/apigen"
	"github.com/cloudcarver/anchor/internal/model"
	"github.com/cloudcarver/anchor/internal/task"
	"github.com/cloudcarver/anchor/internal/task/worker"
	"github.com/cloudcarver/anchor/internal/utils"
)

func init() {
	utils.Noop()
}

const ( {{range .Functions}}
	{{upperFirst .Name}} = "{{.Name}}" 
{{end}})

type TaskRunner interface { {{range .Functions}}
{{.Description}}
	{{upperFirst .Name}}(ctx *model.Context, params *{{.ParameterType}}) error
{{end}}}

type Client struct {
	taskStore task.TaskStoreInterface
	now       func() time.Time
}

func NewTaskRunner(taskStore task.TaskStoreInterface) TaskRunner {
	return &Client{
		taskStore: taskStore,
	}
}

{{range .Functions}}
func (c *Client) {{upperFirst .Name}}(ctx *model.Context, params *{{.ParameterType}}) error {
	payload, err := params.Marshal()
	if err != nil {
		return err
	}

	spec := apigen.TaskSpec{
		Type:    {{upperFirst .Name}},
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	{{if .Timeout }}attributes.Timeout = utils.Ptr("{{.Timeout}}"){{end}}
	{{if .RetryPolicy }}attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:             "{{.RetryPolicy.Interval}}",
		AlwaysRetryOnFailure: {{.RetryPolicy.AlwaysRetryOnFailure}},
	}{{end}}
	{{if .Cronjob }}attributes.Cronjob = &apigen.TaskCronjob{
		CronExpression: "{{.Cronjob.CronExpression}}",
	}{{end}}
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	{{if .Delay }}delay, err := time.ParseDuration("{{.Delay}}")
	if err != nil {
		return fmt.Errorf("failed to parse delay: %w", err)
	}
	task.StartedAt = utils.Ptr(c.now().Add(delay)){{end}}
	if _, err := c.taskStore.PushTask(ctx, task); err != nil {
		return err
	}
	return nil
}{{end}}

{{.StructDefs}}{{range .Functions}}
func (r *{{.ParameterType}}) Parse(spec json.RawMessage) error {
	return json.Unmarshal(spec, r)
}

func (r *{{.ParameterType}}) Marshal() (json.RawMessage, error) {
	return json.Marshal(r)
}{{end}}

type ExecutorInterface interface { {{range .Functions}}
{{.Description}}
	{{upperFirst .Name}}(params *{{.ParameterType}}) error
{{end}}}

type TaskHandler struct {
	executor ExecutorInterface
}

func NewTaskHandler(executor ExecutorInterface) worker.TaskHandler {
	return &TaskHandler{
		executor: executor,
	}
}

func (f *TaskHandler) HandleTask(c *model.Context, spec *apigen.TaskSpec) error {
	switch spec.Type { {{range .Functions}}
	case {{upperFirst .Name}}:
		var params {{.ParameterType}}
		if err := params.Parse(spec.Payload); err != nil {
			return fmt.Errorf("failed to parse {{.Name}} parameters: %w", err)
		}
		return f.executor.{{upperFirst .Name}}(&params)
		{{end}}
	default:
		return fmt.Errorf("unknown handler %s", spec.Type)
	}
}
`
