// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package querier

import (
	"time"

	"github.com/cloudcarver/anclax/pkg/zgen/apigen"
)

type AnclaxAccessKeyPair struct {
	AccessKey string
	SecretKey string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AnclaxAccessRule struct {
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type AnclaxEvent struct {
	ID        int32
	Spec      apigen.EventSpec
	CreatedAt time.Time
}

type AnclaxOpaqueKey struct {
	ID        int64
	Key       []byte
	UserID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AnclaxOrg struct {
	ID        int32
	Name      string
	Tz        string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AnclaxOrgOwner struct {
	OrgID     int32
	UserID    int32
	CreatedAt time.Time
}

type AnclaxOrgUser struct {
	OrgID     int32
	UserID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AnclaxRole struct {
	ID          int32
	OrgID       int32
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type AnclaxRoleAccessRule struct {
	RoleID         int32
	AccessRuleName string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type AnclaxTask struct {
	ID         int32
	Attributes apigen.TaskAttributes
	Spec       apigen.TaskSpec
	Status     string
	UniqueTag  *string
	StartedAt  *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Attempts   int32
}

type AnclaxUser struct {
	ID           int32
	Name         string
	PasswordHash string
	PasswordSalt string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
}

type AnclaxUserDefaultOrg struct {
	UserID    int32
	OrgID     int32
	CreatedAt time.Time
}

type AnclaxUsersRole struct {
	UserID    int32
	RoleID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
