// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package querier

import (
	"time"

	"github.com/cloudcarver/anchor/pkg/zgen/apigen"
)

type AnchorAccessKeyPair struct {
	AccessKey string
	SecretKey string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AnchorAccessRule struct {
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type AnchorEvent struct {
	ID        int32
	Spec      apigen.EventSpec
	CreatedAt time.Time
}

type AnchorOpaqueKey struct {
	ID        int64
	Key       []byte
	UserID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AnchorOrg struct {
	ID        int32
	Name      string
	Tz        string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AnchorOrgOwner struct {
	OrgID     int32
	UserID    int32
	CreatedAt time.Time
}

type AnchorOrgUser struct {
	OrgID     int32
	UserID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AnchorRole struct {
	ID          int32
	OrgID       int32
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type AnchorRoleAccessRule struct {
	RoleID         int32
	AccessRuleName string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type AnchorTask struct {
	ID         int32
	Attributes apigen.TaskAttributes
	Spec       apigen.TaskSpec
	Status     string
	UniqueTag  *string
	StartedAt  *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type AnchorUser struct {
	ID           int32
	Name         string
	PasswordHash string
	PasswordSalt string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type AnchorUsersRole struct {
	UserID    int32
	RoleID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
