// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package querier

import (
	"context"
	"encoding/json"
	"time"

	"github.com/cloudcarver/anclax/pkg/zgen/apigen"
	"github.com/google/uuid"
)

type Querier interface {
	ClaimNormalTaskByGroup(ctx context.Context, arg ClaimNormalTaskByGroupParams) (*AnclaxTask, error)
	ClaimStrictTask(ctx context.Context, arg ClaimStrictTaskParams) (*AnclaxTask, error)
	ClaimTask(ctx context.Context, arg ClaimTaskParams) (*AnclaxTask, error)
	ClaimTaskBatch(ctx context.Context, arg ClaimTaskBatchParams) ([]*AnclaxTask, error)
	ClaimTaskByID(ctx context.Context, arg ClaimTaskByIDParams) (*AnclaxTask, error)
	ClaimWorkerCommand(ctx context.Context, arg ClaimWorkerCommandParams) (*AnclaxTask, error)
	ConfigureWorkerPrefetch(ctx context.Context, arg ConfigureWorkerPrefetchParams) error
	CreateKeyPair(ctx context.Context, arg CreateKeyPairParams) (*AnclaxAccessKeyPair, error)
	CreateOpaqueKey(ctx context.Context, arg CreateOpaqueKeyParams) (int64, error)
	CreateOrg(ctx context.Context, name string) (*AnclaxOrg, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (*AnclaxTask, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*AnclaxUser, error)
	CreateWorkerRuntimeConfig(ctx context.Context, payload json.RawMessage) (*AnclaxWorkerRuntimeConfig, error)
	CreateWorkerRuntimeConfigForRequest(ctx context.Context, arg CreateWorkerRuntimeConfigForRequestParams) (*AnclaxWorkerRuntimeConfig, error)
	DeleteKeyPair(ctx context.Context, accessKey string) error
	DeleteOpaqueKey(ctx context.Context, id int64) error
	DeleteOpaqueKeys(ctx context.Context, group *string) error
	DeleteUserByName(ctx context.Context, name string) error
	DeleteUserByNameReturningID(ctx context.Context, name string) (int32, error)
	EnsureTaskPrefetch(ctx context.Context) error
	FinalizeTaskAttempt(ctx context.Context, arg FinalizeTaskAttemptParams) (string, error)
	GetKeyPair(ctx context.Context, accessKey string) (*AnclaxAccessKeyPair, error)
	GetLastTaskErrorEvent(ctx context.Context, taskID int32) (*AnclaxEvent, error)
	GetLatestWorkerRuntimeConfig(ctx context.Context) (*AnclaxWorkerRuntimeConfig, error)
	GetOpaqueKey(ctx context.Context, id int64) ([]byte, error)
	GetOrg(ctx context.Context, id int32) (*AnclaxOrg, error)
	GetOrgByName(ctx context.Context, name string) (*AnclaxOrg, error)
	GetTaskAttemptStatus(ctx context.Context, arg GetTaskAttemptStatusParams) (string, error)
	GetTaskByID(ctx context.Context, id int32) (*AnclaxTask, error)
	GetTaskByUniqueTag(ctx context.Context, uniqueTag *string) (*AnclaxTask, error)
	GetTaskTagConcurrency(ctx context.Context, tag string) (*AnclaxTaskTagConcurrency, error)
	GetTaskWaitStatusByID(ctx context.Context, id int32) (*GetTaskWaitStatusByIDRow, error)
	GetUser(ctx context.Context, id int32) (*AnclaxUser, error)
	GetUserByName(ctx context.Context, name string) (*AnclaxUser, error)
	GetUserDefaultOrg(ctx context.Context, userID int32) (int32, error)
	GetWorkerRuntimeConfigByVersion(ctx context.Context, version int64) (*AnclaxWorkerRuntimeConfig, error)
	IncrementAttempts(ctx context.Context, id int32) error
	InsertEvent(ctx context.Context, spec apigen.EventSpec) (*AnclaxEvent, error)
	InsertOrgOwner(ctx context.Context, arg InsertOrgOwnerParams) (*AnclaxOrgOwner, error)
	InsertOrgUser(ctx context.Context, arg InsertOrgUserParams) (*AnclaxOrgUser, error)
	// A group_id of -1 denotes a lost scheduler lease. Empty rows mean no supply/work.
	InspectTaskPrefetch(ctx context.Context, arg InspectTaskPrefetchParams) ([]*InspectTaskPrefetchRow, error)
	IsUsernameExists(ctx context.Context, name string) (bool, error)
	ListAllPendingTasks(ctx context.Context) ([]*AnclaxTask, error)
	ListLaggingAliveWorkers(ctx context.Context, arg ListLaggingAliveWorkersParams) ([]uuid.UUID, error)
	ListOnlineWorkerIDs(ctx context.Context, heartbeatCutoff time.Time) ([]uuid.UUID, error)
	ListOrgs(ctx context.Context, userID int32) ([]*AnclaxOrg, error)
	ListTaskDescendantIDs(ctx context.Context, parentTaskID *int32) ([]int32, error)
	ListTaskIDsByTags(ctx context.Context, arg ListTaskIDsByTagsParams) ([]int32, error)
	ListTaskTagConcurrencyLimits(ctx context.Context, arg ListTaskTagConcurrencyLimitsParams) ([]*AnclaxTaskTagConcurrency, error)
	ListTaskWaitStatuses(ctx context.Context, ids []int32) ([]*ListTaskWaitStatusesRow, error)
	ListTerminalTaskWaitStatuses(ctx context.Context, ids []int32) ([]*ListTerminalTaskWaitStatusesRow, error)
	MaintainTaskConcurrency(ctx context.Context, legacyTtlMs int64) error
	MarkWorkerOffline(ctx context.Context, id uuid.UUID) error
	// A negative prepared count means the scheduler attempt no longer owns its lease.
	PrefetchReadyTasks(ctx context.Context, arg PrefetchReadyTasksParams) (int32, error)
	// The wait reason is advisory; allocation and the scheduler fence stay in SQL.
	PrefetchTaskSupply(ctx context.Context, arg PrefetchTaskSupplyParams) (*PrefetchTaskSupplyRow, error)
	RefreshTaskLock(ctx context.Context, arg RefreshTaskLockParams) (int32, error)
	RefreshTaskLocks(ctx context.Context, arg RefreshTaskLocksParams) ([]*RefreshTaskLocksRow, error)
	ReleaseTaskLockByWorker(ctx context.Context, arg ReleaseTaskLockByWorkerParams) (int32, error)
	RemoveTaskTagConcurrencyLimit(ctx context.Context, tag string) error
	RestoreUserByName(ctx context.Context, name string) error
	SetTaskTagConcurrencyLimit(ctx context.Context, arg SetTaskTagConcurrencyLimitParams) error
	SetUserDefaultOrg(ctx context.Context, arg SetUserDefaultOrgParams) error
	UpdatePendingTaskPriorityByLabels(ctx context.Context, arg UpdatePendingTaskPriorityByLabelsParams) (int64, error)
	UpdatePendingTaskWeightByLabels(ctx context.Context, arg UpdatePendingTaskWeightByLabelsParams) (int64, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) error
	UpdateTaskStartedAt(ctx context.Context, arg UpdateTaskStartedAtParams) error
	UpdateTaskStartedAtByWorker(ctx context.Context, arg UpdateTaskStartedAtByWorkerParams) (int32, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error
	UpdateTaskStatusByWorker(ctx context.Context, arg UpdateTaskStatusByWorkerParams) (int32, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateWorkerAppliedConfigVersion(ctx context.Context, arg UpdateWorkerAppliedConfigVersionParams) error
	UpdateWorkerHeartbeat(ctx context.Context, id uuid.UUID) (*AnclaxWorker, error)
	UpgradeUserPasswordHash(ctx context.Context, arg UpgradeUserPasswordHashParams) (int64, error)
	UpsertWorker(ctx context.Context, arg UpsertWorkerParams) (*AnclaxWorker, error)
	VerifyTaskOwnership(ctx context.Context, arg VerifyTaskOwnershipParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
