// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_prefetch.sql

package querier

import (
	"context"

	"github.com/google/uuid"
)

const configureWorkerPrefetch = `-- name: ConfigureWorkerPrefetch :exec
UPDATE anclax.workers SET prefetch_capacity=$1::int,
    prefetch_strict_percentage=COALESCE((SELECT (payload->>'maxStrictPercentage')::int
        FROM anclax.worker_runtime_configs ORDER BY version DESC LIMIT 1),$2::int),
    prefetch_heartbeat_ttl_ms=GREATEST(9000,$3::bigint)
    WHERE id=$4
`

type ConfigureWorkerPrefetchParams struct {
	Capacity         int32
	StrictPercentage int32
	HeartbeatTtlMs   int64
	WorkerID         uuid.UUID
}

func (q *Queries) ConfigureWorkerPrefetch(ctx context.Context, arg ConfigureWorkerPrefetchParams) error {
	_, err := q.db.Exec(ctx, configureWorkerPrefetch,
		arg.Capacity,
		arg.StrictPercentage,
		arg.HeartbeatTtlMs,
		arg.WorkerID,
	)
	return err
}

const ensureTaskPrefetch = `-- name: EnsureTaskPrefetch :exec
INSERT INTO anclax.tasks(attributes,spec,status,unique_tag)
VALUES ('{"retryPolicy":{"interval":"100ms","maxAttempts":-1}}',
    '{"type":"prefetchTasks","payload":{}}','pending','anclax:system:prefetch')
ON CONFLICT(unique_tag) DO NOTHING
`

func (q *Queries) EnsureTaskPrefetch(ctx context.Context) error {
	_, err := q.db.Exec(ctx, ensureTaskPrefetch)
	return err
}

const prefetchReadyTasks = `-- name: PrefetchReadyTasks :one
SELECT anclax.prefetch_ready_tasks($1::int,$2::uuid,
    $3::bigint,$4::int,
    $5::bigint,$6::bigint)::int AS prepared
`

type PrefetchReadyTasksParams struct {
	TaskID       int32
	WorkerID     uuid.UUID
	LeaseVersion int64
	BatchSize    int32
	ReadyTtlMs   int64
	LockTtlMs    int64
}

// A negative prepared count means the scheduler attempt no longer owns its lease.
func (q *Queries) PrefetchReadyTasks(ctx context.Context, arg PrefetchReadyTasksParams) (int32, error) {
	row := q.db.QueryRow(ctx, prefetchReadyTasks,
		arg.TaskID,
		arg.WorkerID,
		arg.LeaseVersion,
		arg.BatchSize,
		arg.ReadyTtlMs,
		arg.LockTtlMs,
	)
	var prepared int32
	err := row.Scan(&prepared)
	return prepared, err
}

const prefetchTaskSupply = `-- name: PrefetchTaskSupply :one
SELECT prepared::int,wait_reason::text
FROM anclax.prefetch_task_supply($1::int,$2::uuid,
    $3::bigint,$4::int,
    $5::bigint,$6::bigint)
`

type PrefetchTaskSupplyParams struct {
	TaskID       int32
	WorkerID     uuid.UUID
	LeaseVersion int64
	BatchSize    int32
	ReadyTtlMs   int64
	LockTtlMs    int64
}

type PrefetchTaskSupplyRow struct {
	Prepared   int32
	WaitReason string
}

// The wait reason is advisory; allocation and the scheduler fence stay in SQL.
func (q *Queries) PrefetchTaskSupply(ctx context.Context, arg PrefetchTaskSupplyParams) (*PrefetchTaskSupplyRow, error) {
	row := q.db.QueryRow(ctx, prefetchTaskSupply,
		arg.TaskID,
		arg.WorkerID,
		arg.LeaseVersion,
		arg.BatchSize,
		arg.ReadyTtlMs,
		arg.LockTtlMs,
	)
	var i PrefetchTaskSupplyRow
	err := row.Scan(&i.Prepared, &i.WaitReason)
	return &i, err
}
