// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tasks.sql

package querier

import (
	"context"
	"time"

	"github.com/cloudcarver/anclax/pkg/zgen/apigen"
	"github.com/google/uuid"
)

const claimTask = `-- name: ClaimTask :one
WITH
    -- Eligible tasks are pending, due, unlocked, and label-compatible.
    eligible AS (
        SELECT t.id, t.attributes, t.spec, t.status, t.unique_tag, t.started_at, t.created_at, t.updated_at, t.attempts, t.locked_at, t.worker_id, t.serial_key, t.serial_id
        FROM anclax.tasks t
        WHERE
            t.status = 'pending'
            AND (t.started_at IS NULL OR t.started_at < NOW())
            AND (t.locked_at IS NULL OR t.locked_at < $2)
            AND (
                $3::bool = false
                OR t.attributes->'labels' IS NULL
                OR jsonb_array_length(t.attributes->'labels') = 0
                OR (t.attributes->'labels' ?| $4::text[])
            )
    ),
    -- Any active lock on a serial key blocks the chain.
    locked_serial_keys AS (
        SELECT DISTINCT t.serial_key
        FROM anclax.tasks t
        WHERE
            t.serial_key IS NOT NULL
            AND t.locked_at IS NOT NULL
            AND t.locked_at >= $2
    ),
    -- A serial task is claimable only if there is no earlier pending task in its chain.
    candidate AS (
        SELECT e.id
        FROM eligible e
        WHERE
            e.serial_key IS NULL
            OR (
                NOT EXISTS (
                    SELECT 1 FROM locked_serial_keys l WHERE l.serial_key = e.serial_key
                )
                AND NOT EXISTS (
                    SELECT 1
                    FROM anclax.tasks s
                    WHERE
                        s.serial_key = e.serial_key
                        AND s.status = 'pending'
                        AND ROW(
                            s.serial_id IS NULL,
                            COALESCE(s.serial_id, 2147483647),
                            s.created_at,
                            COALESCE(s.started_at, '-infinity'::timestamptz),
                            s.id
                        ) < ROW(
                            e.serial_id IS NULL,
                            COALESCE(e.serial_id, 2147483647),
                            e.created_at,
                            COALESCE(e.started_at, '-infinity'::timestamptz),
                            e.id
                        )
                )
            )
        ORDER BY e.created_at, e.id
        LIMIT 1
    )
UPDATE anclax.tasks
SET
    locked_at = CURRENT_TIMESTAMP,
    worker_id = $1,
    attempts = attempts + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE
    anclax.tasks.id = (SELECT id FROM candidate)
    AND anclax.tasks.status = 'pending'
    AND (anclax.tasks.locked_at IS NULL OR anclax.tasks.locked_at < $2)
RETURNING id, attributes, spec, status, unique_tag, started_at, created_at, updated_at, attempts, locked_at, worker_id, serial_key, serial_id
`

type ClaimTaskParams struct {
	WorkerID   uuid.NullUUID
	LockExpiry *time.Time
	HasLabels  bool
	Labels     []string
}

func (q *Queries) ClaimTask(ctx context.Context, arg ClaimTaskParams) (*AnclaxTask, error) {
	row := q.db.QueryRow(ctx, claimTask,
		arg.WorkerID,
		arg.LockExpiry,
		arg.HasLabels,
		arg.Labels,
	)
	var i AnclaxTask
	err := row.Scan(
		&i.ID,
		&i.Attributes,
		&i.Spec,
		&i.Status,
		&i.UniqueTag,
		&i.StartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Attempts,
		&i.LockedAt,
		&i.WorkerID,
		&i.SerialKey,
		&i.SerialID,
	)
	return &i, err
}

const claimTaskByID = `-- name: ClaimTaskByID :one
WITH
    eligible AS (
        SELECT t.id, t.attributes, t.spec, t.status, t.unique_tag, t.started_at, t.created_at, t.updated_at, t.attempts, t.locked_at, t.worker_id, t.serial_key, t.serial_id
        FROM anclax.tasks t
        WHERE
            t.id = $3
            AND t.status = 'pending'
            AND (t.started_at IS NULL OR t.started_at < NOW())
            AND (t.locked_at IS NULL OR t.locked_at < $2)
            AND (
                $4::bool = false
                OR t.attributes->'labels' IS NULL
                OR jsonb_array_length(t.attributes->'labels') = 0
                OR (t.attributes->'labels' ?| $5::text[])
            )
    ),
    locked_serial_keys AS (
        SELECT DISTINCT t.serial_key
        FROM anclax.tasks t
        WHERE
            t.serial_key IS NOT NULL
            AND t.locked_at IS NOT NULL
            AND t.locked_at >= $2
    ),
    candidate AS (
        SELECT e.id
        FROM eligible e
        WHERE
            e.serial_key IS NULL
            OR (
                NOT EXISTS (
                    SELECT 1 FROM locked_serial_keys l WHERE l.serial_key = e.serial_key
                )
                AND NOT EXISTS (
                    SELECT 1
                    FROM anclax.tasks s
                    WHERE
                        s.serial_key = e.serial_key
                        AND s.status = 'pending'
                        AND ROW(
                            s.serial_id IS NULL,
                            COALESCE(s.serial_id, 2147483647),
                            s.created_at,
                            COALESCE(s.started_at, '-infinity'::timestamptz),
                            s.id
                        ) < ROW(
                            e.serial_id IS NULL,
                            COALESCE(e.serial_id, 2147483647),
                            e.created_at,
                            COALESCE(e.started_at, '-infinity'::timestamptz),
                            e.id
                        )
                )
            )
        LIMIT 1
    )
UPDATE anclax.tasks
SET
    locked_at = CURRENT_TIMESTAMP,
    worker_id = $1,
    attempts = attempts + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE
    anclax.tasks.id = (SELECT id FROM candidate)
    AND anclax.tasks.status = 'pending'
    AND (anclax.tasks.locked_at IS NULL OR anclax.tasks.locked_at < $2)
RETURNING id, attributes, spec, status, unique_tag, started_at, created_at, updated_at, attempts, locked_at, worker_id, serial_key, serial_id
`

type ClaimTaskByIDParams struct {
	WorkerID   uuid.NullUUID
	LockExpiry *time.Time
	ID         int32
	HasLabels  bool
	Labels     []string
}

func (q *Queries) ClaimTaskByID(ctx context.Context, arg ClaimTaskByIDParams) (*AnclaxTask, error) {
	row := q.db.QueryRow(ctx, claimTaskByID,
		arg.WorkerID,
		arg.LockExpiry,
		arg.ID,
		arg.HasLabels,
		arg.Labels,
	)
	var i AnclaxTask
	err := row.Scan(
		&i.ID,
		&i.Attributes,
		&i.Spec,
		&i.Status,
		&i.UniqueTag,
		&i.StartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Attempts,
		&i.LockedAt,
		&i.WorkerID,
		&i.SerialKey,
		&i.SerialID,
	)
	return &i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO anclax.tasks (attributes, spec, status, started_at, unique_tag, serial_key, serial_id)
VALUES ($1, $2, $3, $4, $5, $6, $7) ON CONFLICT (unique_tag) DO NOTHING RETURNING id, attributes, spec, status, unique_tag, started_at, created_at, updated_at, attempts, locked_at, worker_id, serial_key, serial_id
`

type CreateTaskParams struct {
	Attributes apigen.TaskAttributes
	Spec       apigen.TaskSpec
	Status     string
	StartedAt  *time.Time
	UniqueTag  *string
	SerialKey  *string
	SerialID   *int32
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (*AnclaxTask, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.Attributes,
		arg.Spec,
		arg.Status,
		arg.StartedAt,
		arg.UniqueTag,
		arg.SerialKey,
		arg.SerialID,
	)
	var i AnclaxTask
	err := row.Scan(
		&i.ID,
		&i.Attributes,
		&i.Spec,
		&i.Status,
		&i.UniqueTag,
		&i.StartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Attempts,
		&i.LockedAt,
		&i.WorkerID,
		&i.SerialKey,
		&i.SerialID,
	)
	return &i, err
}

const getLastTaskErrorEvent = `-- name: GetLastTaskErrorEvent :one
SELECT id, spec, created_at FROM anclax.events
WHERE spec->>'type' = 'TaskError'
  AND (spec->'taskError'->>'taskID')::int = $1::int
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastTaskErrorEvent(ctx context.Context, taskID int32) (*AnclaxEvent, error) {
	row := q.db.QueryRow(ctx, getLastTaskErrorEvent, taskID)
	var i AnclaxEvent
	err := row.Scan(&i.ID, &i.Spec, &i.CreatedAt)
	return &i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, attributes, spec, status, unique_tag, started_at, created_at, updated_at, attempts, locked_at, worker_id, serial_key, serial_id FROM anclax.tasks
WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id int32) (*AnclaxTask, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i AnclaxTask
	err := row.Scan(
		&i.ID,
		&i.Attributes,
		&i.Spec,
		&i.Status,
		&i.UniqueTag,
		&i.StartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Attempts,
		&i.LockedAt,
		&i.WorkerID,
		&i.SerialKey,
		&i.SerialID,
	)
	return &i, err
}

const getTaskByUniqueTag = `-- name: GetTaskByUniqueTag :one
SELECT id, attributes, spec, status, unique_tag, started_at, created_at, updated_at, attempts, locked_at, worker_id, serial_key, serial_id FROM anclax.tasks
WHERE unique_tag = $1
`

func (q *Queries) GetTaskByUniqueTag(ctx context.Context, uniqueTag *string) (*AnclaxTask, error) {
	row := q.db.QueryRow(ctx, getTaskByUniqueTag, uniqueTag)
	var i AnclaxTask
	err := row.Scan(
		&i.ID,
		&i.Attributes,
		&i.Spec,
		&i.Status,
		&i.UniqueTag,
		&i.StartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Attempts,
		&i.LockedAt,
		&i.WorkerID,
		&i.SerialKey,
		&i.SerialID,
	)
	return &i, err
}

const incrementAttempts = `-- name: IncrementAttempts :exec
UPDATE anclax.tasks
SET attempts = attempts + 1, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) IncrementAttempts(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, incrementAttempts, id)
	return err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO anclax.events (spec)
VALUES ($1)
RETURNING id, spec, created_at
`

func (q *Queries) InsertEvent(ctx context.Context, spec apigen.EventSpec) (*AnclaxEvent, error) {
	row := q.db.QueryRow(ctx, insertEvent, spec)
	var i AnclaxEvent
	err := row.Scan(&i.ID, &i.Spec, &i.CreatedAt)
	return &i, err
}

const listAllPendingTasks = `-- name: ListAllPendingTasks :many
SELECT id, attributes, spec, status, unique_tag, started_at, created_at, updated_at, attempts, locked_at, worker_id, serial_key, serial_id FROM anclax.tasks
WHERE
    status = 'pending'
    AND (
        started_at IS NULL OR started_at < NOW()
    )
`

func (q *Queries) ListAllPendingTasks(ctx context.Context) ([]*AnclaxTask, error) {
	rows, err := q.db.Query(ctx, listAllPendingTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*AnclaxTask
	for rows.Next() {
		var i AnclaxTask
		if err := rows.Scan(
			&i.ID,
			&i.Attributes,
			&i.Spec,
			&i.Status,
			&i.UniqueTag,
			&i.StartedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Attempts,
			&i.LockedAt,
			&i.WorkerID,
			&i.SerialKey,
			&i.SerialID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshTaskLock = `-- name: RefreshTaskLock :one
UPDATE anclax.tasks
SET locked_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND worker_id = $2
RETURNING id
`

type RefreshTaskLockParams struct {
	ID       int32
	WorkerID uuid.NullUUID
}

func (q *Queries) RefreshTaskLock(ctx context.Context, arg RefreshTaskLockParams) (int32, error) {
	row := q.db.QueryRow(ctx, refreshTaskLock, arg.ID, arg.WorkerID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const releaseTaskLockByWorker = `-- name: ReleaseTaskLockByWorker :one
UPDATE anclax.tasks
SET locked_at = NULL, worker_id = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND worker_id = $2
RETURNING id
`

type ReleaseTaskLockByWorkerParams struct {
	ID       int32
	WorkerID uuid.NullUUID
}

func (q *Queries) ReleaseTaskLockByWorker(ctx context.Context, arg ReleaseTaskLockByWorkerParams) (int32, error) {
	row := q.db.QueryRow(ctx, releaseTaskLockByWorker, arg.ID, arg.WorkerID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE anclax.tasks
SET
    attributes = $2,
    spec = $3,
    started_at = $4,
    serial_key = $5,
    serial_id = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateTaskParams struct {
	ID         int32
	Attributes apigen.TaskAttributes
	Spec       apigen.TaskSpec
	StartedAt  *time.Time
	SerialKey  *string
	SerialID   *int32
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.Exec(ctx, updateTask,
		arg.ID,
		arg.Attributes,
		arg.Spec,
		arg.StartedAt,
		arg.SerialKey,
		arg.SerialID,
	)
	return err
}

const updateTaskStartedAt = `-- name: UpdateTaskStartedAt :exec
UPDATE anclax.tasks
SET started_at = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateTaskStartedAtParams struct {
	ID        int32
	StartedAt *time.Time
}

func (q *Queries) UpdateTaskStartedAt(ctx context.Context, arg UpdateTaskStartedAtParams) error {
	_, err := q.db.Exec(ctx, updateTaskStartedAt, arg.ID, arg.StartedAt)
	return err
}

const updateTaskStartedAtByWorker = `-- name: UpdateTaskStartedAtByWorker :one
UPDATE anclax.tasks
SET started_at = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND worker_id = $3
RETURNING id
`

type UpdateTaskStartedAtByWorkerParams struct {
	ID        int32
	StartedAt *time.Time
	WorkerID  uuid.NullUUID
}

func (q *Queries) UpdateTaskStartedAtByWorker(ctx context.Context, arg UpdateTaskStartedAtByWorkerParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateTaskStartedAtByWorker, arg.ID, arg.StartedAt, arg.WorkerID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE anclax.tasks
SET 
    status = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateTaskStatusParams struct {
	ID     int32
	Status string
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatus, arg.ID, arg.Status)
	return err
}

const updateTaskStatusByWorker = `-- name: UpdateTaskStatusByWorker :one
UPDATE anclax.tasks
SET
    status = $2,
    locked_at = NULL,
    worker_id = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND worker_id = $3
RETURNING id
`

type UpdateTaskStatusByWorkerParams struct {
	ID       int32
	Status   string
	WorkerID uuid.NullUUID
}

func (q *Queries) UpdateTaskStatusByWorker(ctx context.Context, arg UpdateTaskStatusByWorkerParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateTaskStatusByWorker, arg.ID, arg.Status, arg.WorkerID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const verifyTaskOwnership = `-- name: VerifyTaskOwnership :one
SELECT id FROM anclax.tasks
WHERE id = $1 AND worker_id = $2
`

type VerifyTaskOwnershipParams struct {
	ID       int32
	WorkerID uuid.NullUUID
}

func (q *Queries) VerifyTaskOwnership(ctx context.Context, arg VerifyTaskOwnershipParams) (int32, error) {
	row := q.db.QueryRow(ctx, verifyTaskOwnership, arg.ID, arg.WorkerID)
	var id int32
	err := row.Scan(&id)
	return id, err
}
