// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_prefetch.sql

package querier

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const configureWorkerPrefetch = `-- name: ConfigureWorkerPrefetch :exec
UPDATE anclax.workers SET prefetch_capacity=$1::int,
    prefetch_strict_percentage=COALESCE((SELECT (payload->>'maxStrictPercentage')::int
        FROM anclax.worker_runtime_configs ORDER BY version DESC LIMIT 1),$2::int),
    prefetch_heartbeat_ttl_ms=GREATEST(9000,$3::bigint)
    WHERE id=$4
`

type ConfigureWorkerPrefetchParams struct {
	Capacity         int32
	StrictPercentage int32
	HeartbeatTtlMs   int64
	WorkerID         uuid.UUID
}

func (q *Queries) ConfigureWorkerPrefetch(ctx context.Context, arg ConfigureWorkerPrefetchParams) error {
	_, err := q.db.Exec(ctx, configureWorkerPrefetch,
		arg.Capacity,
		arg.StrictPercentage,
		arg.HeartbeatTtlMs,
		arg.WorkerID,
	)
	return err
}

const ensureTaskPrefetch = `-- name: EnsureTaskPrefetch :exec
INSERT INTO anclax.tasks(attributes,spec,status,unique_tag)
VALUES ('{"retryPolicy":{"interval":"100ms","maxAttempts":-1}}',
    '{"type":"prefetchTasks","payload":{}}','pending','anclax:system:prefetch')
ON CONFLICT(unique_tag) DO NOTHING
`

func (q *Queries) EnsureTaskPrefetch(ctx context.Context) error {
	_, err := q.db.Exec(ctx, ensureTaskPrefetch)
	return err
}

const inspectTaskPrefetch = `-- name: InspectTaskPrefetch :many
SELECT group_id::bigint,ready_count::bigint,has_due::boolean
FROM anclax.inspect_task_prefetch($1::int,$2::uuid,
    $3::bigint,$4::bigint,$5::boolean)
`

type InspectTaskPrefetchParams struct {
	TaskID       int32
	WorkerID     uuid.UUID
	LeaseVersion int64
	LockTtlMs    int64
	Maintain     bool
}

type InspectTaskPrefetchRow struct {
	GroupID    int64
	ReadyCount int64
	HasDue     bool
}

// A group_id of -1 denotes a lost scheduler lease. Empty rows mean no supply/work.
func (q *Queries) InspectTaskPrefetch(ctx context.Context, arg InspectTaskPrefetchParams) ([]*InspectTaskPrefetchRow, error) {
	rows, err := q.db.Query(ctx, inspectTaskPrefetch,
		arg.TaskID,
		arg.WorkerID,
		arg.LeaseVersion,
		arg.LockTtlMs,
		arg.Maintain,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*InspectTaskPrefetchRow
	for rows.Next() {
		var i InspectTaskPrefetchRow
		if err := rows.Scan(&i.GroupID, &i.ReadyCount, &i.HasDue); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const prefetchReadyTasks = `-- name: PrefetchReadyTasks :one
SELECT anclax.prefetch_ready_tasks($1::int,$2::uuid,
    $3::bigint,$4::int,
    $5::bigint)::int AS prepared
`

type PrefetchReadyTasksParams struct {
	TaskID       int32
	WorkerID     uuid.UUID
	LeaseVersion int64
	BatchSize    int32
	LockTtlMs    int64
}

// A negative prepared count means the scheduler attempt no longer owns its lease.
func (q *Queries) PrefetchReadyTasks(ctx context.Context, arg PrefetchReadyTasksParams) (int32, error) {
	row := q.db.QueryRow(ctx, prefetchReadyTasks,
		arg.TaskID,
		arg.WorkerID,
		arg.LeaseVersion,
		arg.BatchSize,
		arg.LockTtlMs,
	)
	var prepared int32
	err := row.Scan(&prepared)
	return prepared, err
}

const prefetchTaskSupply = `-- name: PrefetchTaskSupply :one
SELECT prepared::int,wait_reason::text,prepared_groups::jsonb
FROM anclax.prefetch_task_supply($1::int,$2::uuid,
    $3::bigint,$4::int,
    $5::bigint,$6::bigint[])
`

type PrefetchTaskSupplyParams struct {
	TaskID       int32
	WorkerID     uuid.UUID
	LeaseVersion int64
	BatchSize    int32
	LockTtlMs    int64
	PausedGroups []int64
}

type PrefetchTaskSupplyRow struct {
	Prepared       int32
	WaitReason     string
	PreparedGroups json.RawMessage
}

// The wait reason is advisory; allocation and the scheduler fence stay in SQL.
func (q *Queries) PrefetchTaskSupply(ctx context.Context, arg PrefetchTaskSupplyParams) (*PrefetchTaskSupplyRow, error) {
	row := q.db.QueryRow(ctx, prefetchTaskSupply,
		arg.TaskID,
		arg.WorkerID,
		arg.LeaseVersion,
		arg.BatchSize,
		arg.LockTtlMs,
		arg.PausedGroups,
	)
	var i PrefetchTaskSupplyRow
	err := row.Scan(&i.Prepared, &i.WaitReason, &i.PreparedGroups)
	return &i, err
}
