// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_tag_concurrency.sql

package querier

import (
	"context"
)

const getTaskTagConcurrency = `-- name: GetTaskTagConcurrency :one
SELECT tag, max_concurrency, in_use FROM anclax.task_tag_concurrency WHERE tag = $1
`

func (q *Queries) GetTaskTagConcurrency(ctx context.Context, tag string) (*AnclaxTaskTagConcurrency, error) {
	row := q.db.QueryRow(ctx, getTaskTagConcurrency, tag)
	var i AnclaxTaskTagConcurrency
	err := row.Scan(&i.Tag, &i.MaxConcurrency, &i.InUse)
	return &i, err
}

const listTaskTagConcurrencyLimits = `-- name: ListTaskTagConcurrencyLimits :many
SELECT tag, max_concurrency, in_use FROM anclax.task_tag_concurrency
WHERE max_concurrency IS NOT NULL AND tag > $1::text
ORDER BY tag LIMIT $2::int
`

type ListTaskTagConcurrencyLimitsParams struct {
	AfterTag string
	PageSize int32
}

func (q *Queries) ListTaskTagConcurrencyLimits(ctx context.Context, arg ListTaskTagConcurrencyLimitsParams) ([]*AnclaxTaskTagConcurrency, error) {
	rows, err := q.db.Query(ctx, listTaskTagConcurrencyLimits, arg.AfterTag, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*AnclaxTaskTagConcurrency
	for rows.Next() {
		var i AnclaxTaskTagConcurrency
		if err := rows.Scan(&i.Tag, &i.MaxConcurrency, &i.InUse); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maintainTaskConcurrency = `-- name: MaintainTaskConcurrency :exec
SELECT anclax.maintain_task_concurrency($1::bigint)
`

func (q *Queries) MaintainTaskConcurrency(ctx context.Context, legacyTtlMs int64) error {
	_, err := q.db.Exec(ctx, maintainTaskConcurrency, legacyTtlMs)
	return err
}

const removeTaskTagConcurrencyLimit = `-- name: RemoveTaskTagConcurrencyLimit :exec
UPDATE anclax.task_tag_concurrency SET max_concurrency = NULL WHERE tag = $1
`

func (q *Queries) RemoveTaskTagConcurrencyLimit(ctx context.Context, tag string) error {
	_, err := q.db.Exec(ctx, removeTaskTagConcurrencyLimit, tag)
	return err
}

const setTaskTagConcurrencyLimit = `-- name: SetTaskTagConcurrencyLimit :exec
INSERT INTO anclax.task_tag_concurrency (tag, max_concurrency)
VALUES ($1, $2::int)
ON CONFLICT (tag) DO UPDATE SET max_concurrency = EXCLUDED.max_concurrency
`

type SetTaskTagConcurrencyLimitParams struct {
	Tag            string
	MaxConcurrency int32
}

func (q *Queries) SetTaskTagConcurrencyLimit(ctx context.Context, arg SetTaskTagConcurrencyLimitParams) error {
	_, err := q.db.Exec(ctx, setTaskTagConcurrencyLimit, arg.Tag, arg.MaxConcurrency)
	return err
}
