// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_batch.sql

package querier

import (
	"context"

	"github.com/google/uuid"
)

const claimTaskBatch = `-- name: ClaimTaskBatch :many
WITH strict_candidates AS MATERIALIZED (
    SELECT t.id, t.priority, t.weight, t.created_at, 0::int AS group_order
    FROM anclax.tasks t
    WHERE t.status = 'ready'
        AND t.priority > 0
        AND NOT EXISTS (
            SELECT 1 FROM jsonb_array_elements_text(COALESCE(NULLIF(t.attributes->'labels', 'null'::jsonb), '[]'::jsonb)) AS task_label(value)
            WHERE NOT (task_label.value = ANY(COALESCE($3::text[], ARRAY[]::text[])))
        )
    ORDER BY t.priority DESC, t.created_at, t.id
    LIMIT $4::int
    FOR UPDATE OF t SKIP LOCKED
), normal_candidates AS MATERIALIZED (
    SELECT t.id, t.priority, t.weight, t.created_at, array_position($5::text[], COALESCE((SELECT MIN(label) FROM jsonb_array_elements_text(COALESCE(NULLIF(t.attributes->'labels', 'null'::jsonb), '[]'::jsonb)) AS labels(label) WHERE label = ANY($6::text[])), '__default__')) AS group_order
    FROM anclax.tasks t
    WHERE t.status = 'ready'
        AND t.priority = 0
        AND COALESCE((SELECT MIN(label) FROM jsonb_array_elements_text(COALESCE(NULLIF(t.attributes->'labels', 'null'::jsonb), '[]'::jsonb)) AS labels(label) WHERE label = ANY($6::text[])), '__default__') = ANY($5::text[])
        AND NOT EXISTS (
            SELECT 1 FROM jsonb_array_elements_text(COALESCE(NULLIF(t.attributes->'labels', 'null'::jsonb), '[]'::jsonb)) AS task_label(value)
            WHERE NOT (task_label.value = ANY(COALESCE($3::text[], ARRAY[]::text[])))
        )
    ORDER BY group_order, t.weight DESC, t.created_at, t.id
    LIMIT $7::int
    FOR UPDATE OF t SKIP LOCKED
), candidate AS MATERIALIZED (
    SELECT id, priority, weight, created_at, group_order FROM (SELECT id, priority, weight, created_at, group_order FROM strict_candidates UNION ALL SELECT id, priority, weight, created_at, group_order FROM normal_candidates) candidates
    ORDER BY priority DESC,group_order,CASE WHEN priority=0 THEN weight ELSE 0 END DESC,created_at,id
    LIMIT $7::int
)
UPDATE anclax.tasks AS t
SET status='running',locked_at=statement_timestamp(),worker_id=$1,
    lease_expires_at=statement_timestamp()+$2::bigint*INTERVAL '1 millisecond',
    lease_duration_ms=$2::bigint,attempts=t.attempts+1,updated_at=statement_timestamp()
FROM candidate WHERE t.id=candidate.id RETURNING t.id, t.attributes, t.spec, t.status, t.unique_tag, t.started_at, t.created_at, t.updated_at, t.attempts, t.locked_at, t.worker_id, t.serial_key, t.serial_id, t.priority, t.weight, t.parent_task_id, t.lease_version, t.lease_expires_at, t.lease_duration_ms, t.lease_tags, t.admission_group_id
`

type ClaimTaskBatchParams struct {
	WorkerID       uuid.NullUUID
	LockTtlMs      int64
	Labels         []string
	StrictSlots    int32
	GroupNames     []string
	WeightedLabels []string
	BatchSize      int32
}

func (q *Queries) ClaimTaskBatch(ctx context.Context, arg ClaimTaskBatchParams) ([]*AnclaxTask, error) {
	rows, err := q.db.Query(ctx, claimTaskBatch,
		arg.WorkerID,
		arg.LockTtlMs,
		arg.Labels,
		arg.StrictSlots,
		arg.GroupNames,
		arg.WeightedLabels,
		arg.BatchSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*AnclaxTask
	for rows.Next() {
		var i AnclaxTask
		if err := rows.Scan(
			&i.ID,
			&i.Attributes,
			&i.Spec,
			&i.Status,
			&i.UniqueTag,
			&i.StartedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Attempts,
			&i.LockedAt,
			&i.WorkerID,
			&i.SerialKey,
			&i.SerialID,
			&i.Priority,
			&i.Weight,
			&i.ParentTaskID,
			&i.LeaseVersion,
			&i.LeaseExpiresAt,
			&i.LeaseDurationMs,
			&i.LeaseTags,
			&i.AdmissionGroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
