// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package querier

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO anchor.users (
    name,
    password_hash,
    password_salt
) VALUES (
    $1, $2, $3
) RETURNING id, name, password_hash, password_salt, created_at, updated_at
`

type CreateUserParams struct {
	Name         string
	PasswordHash string
	PasswordSalt string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*AnchorUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.PasswordHash, arg.PasswordSalt)
	var i AnchorUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteUserByName = `-- name: DeleteUserByName :exec
DELETE FROM anchor.users
WHERE name = $1
`

func (q *Queries) DeleteUserByName(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteUserByName, name)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, name, password_hash, password_salt, created_at, updated_at FROM anchor.users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (*AnchorUser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i AnchorUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, name, password_hash, password_salt, created_at, updated_at FROM anchor.users
WHERE name = $1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (*AnchorUser, error) {
	row := q.db.QueryRow(ctx, getUserByName, name)
	var i AnchorUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
