// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/taskcore/interfaces.go
//
// Generated by this command:
//
//	mockgen -source pkg/taskcore/interfaces.go -destination pkg/taskcore/mock_gen.go -package taskcore
//

// Package taskcore is a generated GoMock package.
package taskcore

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	core "github.com/cloudcarver/anclax/core"
	apigen "github.com/cloudcarver/anclax/pkg/zgen/apigen"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskStoreInterface is a mock of TaskStoreInterface interface.
type MockTaskStoreInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTaskStoreInterfaceMockRecorder
	isgomock struct{}
}

// MockTaskStoreInterfaceMockRecorder is the mock recorder for MockTaskStoreInterface.
type MockTaskStoreInterfaceMockRecorder struct {
	mock *MockTaskStoreInterface
}

// NewMockTaskStoreInterface creates a new mock instance.
func NewMockTaskStoreInterface(ctrl *gomock.Controller) *MockTaskStoreInterface {
	mock := &MockTaskStoreInterface{ctrl: ctrl}
	mock.recorder = &MockTaskStoreInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskStoreInterface) EXPECT() *MockTaskStoreInterfaceMockRecorder {
	return m.recorder
}

// GetLastTaskErrorEvent mocks base method.
func (m *MockTaskStoreInterface) GetLastTaskErrorEvent(ctx context.Context, taskID int32) (*apigen.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastTaskErrorEvent", ctx, taskID)
	ret0, _ := ret[0].(*apigen.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastTaskErrorEvent indicates an expected call of GetLastTaskErrorEvent.
func (mr *MockTaskStoreInterfaceMockRecorder) GetLastTaskErrorEvent(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastTaskErrorEvent", reflect.TypeOf((*MockTaskStoreInterface)(nil).GetLastTaskErrorEvent), ctx, taskID)
}

// GetTaskByID mocks base method.
func (m *MockTaskStoreInterface) GetTaskByID(ctx context.Context, taskID int32) (*apigen.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByID", ctx, taskID)
	ret0, _ := ret[0].(*apigen.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByID indicates an expected call of GetTaskByID.
func (mr *MockTaskStoreInterfaceMockRecorder) GetTaskByID(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByID", reflect.TypeOf((*MockTaskStoreInterface)(nil).GetTaskByID), ctx, taskID)
}

// GetTaskByUniqueTag mocks base method.
func (m *MockTaskStoreInterface) GetTaskByUniqueTag(ctx context.Context, uniqueTag string) (*apigen.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByUniqueTag", ctx, uniqueTag)
	ret0, _ := ret[0].(*apigen.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByUniqueTag indicates an expected call of GetTaskByUniqueTag.
func (mr *MockTaskStoreInterfaceMockRecorder) GetTaskByUniqueTag(ctx, uniqueTag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByUniqueTag", reflect.TypeOf((*MockTaskStoreInterface)(nil).GetTaskByUniqueTag), ctx, uniqueTag)
}

// PauseTask mocks base method.
func (m *MockTaskStoreInterface) PauseTask(ctx context.Context, taskID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseTask", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PauseTask indicates an expected call of PauseTask.
func (mr *MockTaskStoreInterfaceMockRecorder) PauseTask(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseTask", reflect.TypeOf((*MockTaskStoreInterface)(nil).PauseTask), ctx, taskID)
}

// PushTask mocks base method.
func (m *MockTaskStoreInterface) PushTask(ctx context.Context, task *apigen.Task) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushTask", ctx, task)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PushTask indicates an expected call of PushTask.
func (mr *MockTaskStoreInterfaceMockRecorder) PushTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushTask", reflect.TypeOf((*MockTaskStoreInterface)(nil).PushTask), ctx, task)
}

// ResumeTask mocks base method.
func (m *MockTaskStoreInterface) ResumeTask(ctx context.Context, taskID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeTask", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResumeTask indicates an expected call of ResumeTask.
func (mr *MockTaskStoreInterfaceMockRecorder) ResumeTask(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeTask", reflect.TypeOf((*MockTaskStoreInterface)(nil).ResumeTask), ctx, taskID)
}

// UpdateCronJob mocks base method.
func (m *MockTaskStoreInterface) UpdateCronJob(ctx context.Context, taskID int32, cronExpression string, spec json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCronJob", ctx, taskID, cronExpression, spec)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCronJob indicates an expected call of UpdateCronJob.
func (mr *MockTaskStoreInterfaceMockRecorder) UpdateCronJob(ctx, taskID, cronExpression, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCronJob", reflect.TypeOf((*MockTaskStoreInterface)(nil).UpdateCronJob), ctx, taskID, cronExpression, spec)
}

// UpdatePendingTaskPriorityByLabels mocks base method.
func (m *MockTaskStoreInterface) UpdatePendingTaskPriorityByLabels(ctx context.Context, labels []string, priority int32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePendingTaskPriorityByLabels", ctx, labels, priority)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePendingTaskPriorityByLabels indicates an expected call of UpdatePendingTaskPriorityByLabels.
func (mr *MockTaskStoreInterfaceMockRecorder) UpdatePendingTaskPriorityByLabels(ctx, labels, priority any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePendingTaskPriorityByLabels", reflect.TypeOf((*MockTaskStoreInterface)(nil).UpdatePendingTaskPriorityByLabels), ctx, labels, priority)
}

// UpdatePendingTaskWeightByLabels mocks base method.
func (m *MockTaskStoreInterface) UpdatePendingTaskWeightByLabels(ctx context.Context, labels []string, weight int32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePendingTaskWeightByLabels", ctx, labels, weight)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePendingTaskWeightByLabels indicates an expected call of UpdatePendingTaskWeightByLabels.
func (mr *MockTaskStoreInterfaceMockRecorder) UpdatePendingTaskWeightByLabels(ctx, labels, weight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePendingTaskWeightByLabels", reflect.TypeOf((*MockTaskStoreInterface)(nil).UpdatePendingTaskWeightByLabels), ctx, labels, weight)
}

// WaitForTask mocks base method.
func (m *MockTaskStoreInterface) WaitForTask(ctx context.Context, taskID int32, opts ...WaitForTaskOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, taskID}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WaitForTask", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForTask indicates an expected call of WaitForTask.
func (mr *MockTaskStoreInterfaceMockRecorder) WaitForTask(ctx, taskID any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, taskID}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForTask", reflect.TypeOf((*MockTaskStoreInterface)(nil).WaitForTask), varargs...)
}

// WithTx mocks base method.
func (m *MockTaskStoreInterface) WithTx(tx core.Tx) TaskStoreInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(TaskStoreInterface)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockTaskStoreInterfaceMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockTaskStoreInterface)(nil).WithTx), tx)
}
