// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/cloudcarver/anchor/wire"
	"myexampleapp/pkg"
	"myexampleapp/pkg/asynctask"
	"myexampleapp/pkg/config"
	"myexampleapp/pkg/handler"
	"myexampleapp/pkg/zcore/injection"
	"myexampleapp/pkg/zcore/model"
	"myexampleapp/pkg/zgen/taskgen"
)

// Injectors from wire.go:

func InitApp() (*pkg.App, error) {
	application, err := wire.InitializeApplication()
	if err != nil {
		return nil, err
	}
	serviceInterface := injection.InjectAnchorSvc(application)
	taskStoreInterface := injection.InjectTaskStore(application)
	taskRunner := taskgen.NewTaskRunner(taskStoreInterface)
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	modelInterface, err := model.NewModel(configConfig)
	if err != nil {
		return nil, err
	}
	executorInterface := asynctask.NewExecutor(modelInterface)
	taskHandler := taskgen.NewTaskHandler(executorInterface)
	serverInterface, err := handler.NewHandler(modelInterface, taskRunner)
	if err != nil {
		return nil, err
	}
	authInterface := injection.InjectAuth(application)
	validator := handler.NewValidator(authInterface)
	app, err := pkg.NewApp(application, serviceInterface, taskRunner, taskHandler, serverInterface, validator)
	if err != nil {
		return nil, err
	}
	return app, nil
}
