// This file is generated by tools, DO NOT EDIT.
package taskgen

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"

	"github.com/cloudcarver/anclax/core"
	"github.com/cloudcarver/anclax/pkg/zgen/apigen"
	taskcore "github.com/cloudcarver/anclax/pkg/taskcore/store"
	"github.com/cloudcarver/anclax/pkg/taskcore/worker"
	"github.com/cloudcarver/anclax/pkg/utils"
	"github.com/pkg/errors"
)

func init() {
	utils.Noop()
}

const ( 
	DeleteOpaqueKey = "deleteOpaqueKey" 

	UpdateWorkerRuntimeConfig = "updateWorkerRuntimeConfig" 

	InterruptTask = "interruptTask" 

	BroadcastUpdateWorkerRuntimeConfig = "broadcastUpdateWorkerRuntimeConfig" 

	ApplyWorkerRuntimeConfigToWorker = "applyWorkerRuntimeConfigToWorker" 

	BroadcastCancelTask = "broadcastCancelTask" 

	CancelTaskOnWorker = "cancelTaskOnWorker" 

	BroadcastPauseTask = "broadcastPauseTask" 

	PauseTaskOnWorker = "pauseTaskOnWorker" 

	StressProbe = "stressProbe" 

	CancelObservableProbe = "cancelObservableProbe" 
)



type TaskRunner interface { 
    // Delete an opaque key
	RunDeleteOpaqueKey(ctx context.Context, params *DeleteOpaqueKeyParameters, overrides ...taskcore.TaskOverride) (int32, error)
    // Delete an opaque key
	RunDeleteOpaqueKeyWithTx(ctx context.Context, tx core.Tx, params *DeleteOpaqueKeyParameters, overrides ...taskcore.TaskOverride) (int32, error)

    // Update worker runtime config and wait for alive workers to apply it
	RunUpdateWorkerRuntimeConfig(ctx context.Context, params *UpdateWorkerRuntimeConfigParameters, overrides ...taskcore.TaskOverride) (int32, error)
    // Update worker runtime config and wait for alive workers to apply it
	RunUpdateWorkerRuntimeConfigWithTx(ctx context.Context, tx core.Tx, params *UpdateWorkerRuntimeConfigParameters, overrides ...taskcore.TaskOverride) (int32, error)

    // Interrupt a task and stop any in-flight execution
	RunInterruptTask(ctx context.Context, params *InterruptTaskParameters, overrides ...taskcore.TaskOverride) (int32, error)
    // Interrupt a task and stop any in-flight execution
	RunInterruptTaskWithTx(ctx context.Context, tx core.Tx, params *InterruptTaskParameters, overrides ...taskcore.TaskOverride) (int32, error)

    // Broadcast a runtime config update command to all alive workers
	RunBroadcastUpdateWorkerRuntimeConfig(ctx context.Context, params *BroadcastUpdateWorkerRuntimeConfigParameters, overrides ...taskcore.TaskOverride) (int32, error)
    // Broadcast a runtime config update command to all alive workers
	RunBroadcastUpdateWorkerRuntimeConfigWithTx(ctx context.Context, tx core.Tx, params *BroadcastUpdateWorkerRuntimeConfigParameters, overrides ...taskcore.TaskOverride) (int32, error)

    // Apply a runtime config version on one specific worker
	RunApplyWorkerRuntimeConfigToWorker(ctx context.Context, params *ApplyWorkerRuntimeConfigToWorkerParameters, overrides ...taskcore.TaskOverride) (int32, error)
    // Apply a runtime config version on one specific worker
	RunApplyWorkerRuntimeConfigToWorkerWithTx(ctx context.Context, tx core.Tx, params *ApplyWorkerRuntimeConfigToWorkerParameters, overrides ...taskcore.TaskOverride) (int32, error)

    // Broadcast cancel-task command to alive workers
	RunBroadcastCancelTask(ctx context.Context, params *BroadcastCancelTaskParameters, overrides ...taskcore.TaskOverride) (int32, error)
    // Broadcast cancel-task command to alive workers
	RunBroadcastCancelTaskWithTx(ctx context.Context, tx core.Tx, params *BroadcastCancelTaskParameters, overrides ...taskcore.TaskOverride) (int32, error)

    // Cancel in-flight task execution on one specific worker
	RunCancelTaskOnWorker(ctx context.Context, params *CancelTaskOnWorkerParameters, overrides ...taskcore.TaskOverride) (int32, error)
    // Cancel in-flight task execution on one specific worker
	RunCancelTaskOnWorkerWithTx(ctx context.Context, tx core.Tx, params *CancelTaskOnWorkerParameters, overrides ...taskcore.TaskOverride) (int32, error)

    // Broadcast pause-task command to alive workers
	RunBroadcastPauseTask(ctx context.Context, params *BroadcastPauseTaskParameters, overrides ...taskcore.TaskOverride) (int32, error)
    // Broadcast pause-task command to alive workers
	RunBroadcastPauseTaskWithTx(ctx context.Context, tx core.Tx, params *BroadcastPauseTaskParameters, overrides ...taskcore.TaskOverride) (int32, error)

    // Pause in-flight task execution on one specific worker
	RunPauseTaskOnWorker(ctx context.Context, params *PauseTaskOnWorkerParameters, overrides ...taskcore.TaskOverride) (int32, error)
    // Pause in-flight task execution on one specific worker
	RunPauseTaskOnWorkerWithTx(ctx context.Context, tx core.Tx, params *PauseTaskOnWorkerParameters, overrides ...taskcore.TaskOverride) (int32, error)

    // No-op stress probe task for worker E2E benchmarking
	RunStressProbe(ctx context.Context, params *StressProbeParameters, overrides ...taskcore.TaskOverride) (int32, error)
    // No-op stress probe task for worker E2E benchmarking
	RunStressProbeWithTx(ctx context.Context, tx core.Tx, params *StressProbeParameters, overrides ...taskcore.TaskOverride) (int32, error)

    // Long-running observable task used to validate cancellation semantics under chaos
	RunCancelObservableProbe(ctx context.Context, params *CancelObservableProbeParameters, overrides ...taskcore.TaskOverride) (int32, error)
    // Long-running observable task used to validate cancellation semantics under chaos
	RunCancelObservableProbeWithTx(ctx context.Context, tx core.Tx, params *CancelObservableProbeParameters, overrides ...taskcore.TaskOverride) (int32, error)
}

type Client struct {
	taskStore taskcore.TaskStoreInterface
	now       func() time.Time
}

func NewTaskRunner(taskStore taskcore.TaskStoreInterface) TaskRunner {
	return &Client{
		taskStore: taskStore,
		now:       time.Now,
	}
}


func (c *Client) RunDeleteOpaqueKey(ctx context.Context, params *DeleteOpaqueKeyParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runDeleteOpaqueKey(ctx, c.taskStore, nil, params, overrides...)
}

func (c *Client) RunDeleteOpaqueKeyWithTx(ctx context.Context, tx core.Tx, params *DeleteOpaqueKeyParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runDeleteOpaqueKey(ctx, c.taskStore, tx, params, overrides...)
}

func (c *Client) runDeleteOpaqueKey(ctx context.Context, taskstore taskcore.TaskStoreInterface, tx core.Tx, params *DeleteOpaqueKeyParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	payload, err := json.Marshal(params)
	if err != nil {
		return 0, err
	}

	spec := apigen.TaskSpec{
		Type:    DeleteOpaqueKey,
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	
	attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:    "30m",
		MaxAttempts: -1,
	}
	
	
	
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	
	for _, override := range overrides {
		if err := override(task); err != nil {
			return 0, errors.Wrap(err, "failed to apply task override")
		}
	}
	var taskID int32
	if tx == nil {
		taskID, err = taskstore.PushTask(ctx, task)
	} else {
		taskID, err = taskstore.PushTaskWithTx(ctx, tx, task)
	}
	if err != nil {
		return 0, err
	}
	return taskID, nil
}
func (c *Client) RunUpdateWorkerRuntimeConfig(ctx context.Context, params *UpdateWorkerRuntimeConfigParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runUpdateWorkerRuntimeConfig(ctx, c.taskStore, nil, params, overrides...)
}

func (c *Client) RunUpdateWorkerRuntimeConfigWithTx(ctx context.Context, tx core.Tx, params *UpdateWorkerRuntimeConfigParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runUpdateWorkerRuntimeConfig(ctx, c.taskStore, tx, params, overrides...)
}

func (c *Client) runUpdateWorkerRuntimeConfig(ctx context.Context, taskstore taskcore.TaskStoreInterface, tx core.Tx, params *UpdateWorkerRuntimeConfigParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	payload, err := json.Marshal(params)
	if err != nil {
		return 0, err
	}

	spec := apigen.TaskSpec{
		Type:    UpdateWorkerRuntimeConfig,
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	attributes.Timeout = utils.Ptr("5m")
	attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:    "2s",
		MaxAttempts: -1,
	}
	
	
	attributes.Priority = utils.Ptr(int32(2147483647))
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	
	for _, override := range overrides {
		if err := override(task); err != nil {
			return 0, errors.Wrap(err, "failed to apply task override")
		}
	}
	var taskID int32
	if tx == nil {
		taskID, err = taskstore.PushTask(ctx, task)
	} else {
		taskID, err = taskstore.PushTaskWithTx(ctx, tx, task)
	}
	if err != nil {
		return 0, err
	}
	return taskID, nil
}
func (c *Client) RunInterruptTask(ctx context.Context, params *InterruptTaskParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runInterruptTask(ctx, c.taskStore, nil, params, overrides...)
}

func (c *Client) RunInterruptTaskWithTx(ctx context.Context, tx core.Tx, params *InterruptTaskParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runInterruptTask(ctx, c.taskStore, tx, params, overrides...)
}

func (c *Client) runInterruptTask(ctx context.Context, taskstore taskcore.TaskStoreInterface, tx core.Tx, params *InterruptTaskParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	payload, err := json.Marshal(params)
	if err != nil {
		return 0, err
	}

	spec := apigen.TaskSpec{
		Type:    InterruptTask,
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	attributes.Timeout = utils.Ptr("5m")
	attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:    "2s",
		MaxAttempts: -1,
	}
	
	
	attributes.Priority = utils.Ptr(int32(2147483647))
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	
	for _, override := range overrides {
		if err := override(task); err != nil {
			return 0, errors.Wrap(err, "failed to apply task override")
		}
	}
	var taskID int32
	if tx == nil {
		taskID, err = taskstore.PushTask(ctx, task)
	} else {
		taskID, err = taskstore.PushTaskWithTx(ctx, tx, task)
	}
	if err != nil {
		return 0, err
	}
	return taskID, nil
}
func (c *Client) RunBroadcastUpdateWorkerRuntimeConfig(ctx context.Context, params *BroadcastUpdateWorkerRuntimeConfigParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runBroadcastUpdateWorkerRuntimeConfig(ctx, c.taskStore, nil, params, overrides...)
}

func (c *Client) RunBroadcastUpdateWorkerRuntimeConfigWithTx(ctx context.Context, tx core.Tx, params *BroadcastUpdateWorkerRuntimeConfigParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runBroadcastUpdateWorkerRuntimeConfig(ctx, c.taskStore, tx, params, overrides...)
}

func (c *Client) runBroadcastUpdateWorkerRuntimeConfig(ctx context.Context, taskstore taskcore.TaskStoreInterface, tx core.Tx, params *BroadcastUpdateWorkerRuntimeConfigParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	payload, err := json.Marshal(params)
	if err != nil {
		return 0, err
	}

	spec := apigen.TaskSpec{
		Type:    BroadcastUpdateWorkerRuntimeConfig,
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	attributes.Timeout = utils.Ptr("5m")
	attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:    "2s",
		MaxAttempts: -1,
	}
	
	
	attributes.Priority = utils.Ptr(int32(2147483647))
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	
	for _, override := range overrides {
		if err := override(task); err != nil {
			return 0, errors.Wrap(err, "failed to apply task override")
		}
	}
	var taskID int32
	if tx == nil {
		taskID, err = taskstore.PushTask(ctx, task)
	} else {
		taskID, err = taskstore.PushTaskWithTx(ctx, tx, task)
	}
	if err != nil {
		return 0, err
	}
	return taskID, nil
}
func (c *Client) RunApplyWorkerRuntimeConfigToWorker(ctx context.Context, params *ApplyWorkerRuntimeConfigToWorkerParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runApplyWorkerRuntimeConfigToWorker(ctx, c.taskStore, nil, params, overrides...)
}

func (c *Client) RunApplyWorkerRuntimeConfigToWorkerWithTx(ctx context.Context, tx core.Tx, params *ApplyWorkerRuntimeConfigToWorkerParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runApplyWorkerRuntimeConfigToWorker(ctx, c.taskStore, tx, params, overrides...)
}

func (c *Client) runApplyWorkerRuntimeConfigToWorker(ctx context.Context, taskstore taskcore.TaskStoreInterface, tx core.Tx, params *ApplyWorkerRuntimeConfigToWorkerParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	payload, err := json.Marshal(params)
	if err != nil {
		return 0, err
	}

	spec := apigen.TaskSpec{
		Type:    ApplyWorkerRuntimeConfigToWorker,
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	attributes.Timeout = utils.Ptr("5m")
	attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:    "1s",
		MaxAttempts: -1,
	}
	
	
	attributes.Priority = utils.Ptr(int32(2147483647))
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	
	for _, override := range overrides {
		if err := override(task); err != nil {
			return 0, errors.Wrap(err, "failed to apply task override")
		}
	}
	var taskID int32
	if tx == nil {
		taskID, err = taskstore.PushTask(ctx, task)
	} else {
		taskID, err = taskstore.PushTaskWithTx(ctx, tx, task)
	}
	if err != nil {
		return 0, err
	}
	return taskID, nil
}
func (c *Client) RunBroadcastCancelTask(ctx context.Context, params *BroadcastCancelTaskParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runBroadcastCancelTask(ctx, c.taskStore, nil, params, overrides...)
}

func (c *Client) RunBroadcastCancelTaskWithTx(ctx context.Context, tx core.Tx, params *BroadcastCancelTaskParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runBroadcastCancelTask(ctx, c.taskStore, tx, params, overrides...)
}

func (c *Client) runBroadcastCancelTask(ctx context.Context, taskstore taskcore.TaskStoreInterface, tx core.Tx, params *BroadcastCancelTaskParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	payload, err := json.Marshal(params)
	if err != nil {
		return 0, err
	}

	spec := apigen.TaskSpec{
		Type:    BroadcastCancelTask,
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	attributes.Timeout = utils.Ptr("5m")
	attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:    "2s",
		MaxAttempts: -1,
	}
	
	
	attributes.Priority = utils.Ptr(int32(2147483647))
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	
	for _, override := range overrides {
		if err := override(task); err != nil {
			return 0, errors.Wrap(err, "failed to apply task override")
		}
	}
	var taskID int32
	if tx == nil {
		taskID, err = taskstore.PushTask(ctx, task)
	} else {
		taskID, err = taskstore.PushTaskWithTx(ctx, tx, task)
	}
	if err != nil {
		return 0, err
	}
	return taskID, nil
}
func (c *Client) RunCancelTaskOnWorker(ctx context.Context, params *CancelTaskOnWorkerParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runCancelTaskOnWorker(ctx, c.taskStore, nil, params, overrides...)
}

func (c *Client) RunCancelTaskOnWorkerWithTx(ctx context.Context, tx core.Tx, params *CancelTaskOnWorkerParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runCancelTaskOnWorker(ctx, c.taskStore, tx, params, overrides...)
}

func (c *Client) runCancelTaskOnWorker(ctx context.Context, taskstore taskcore.TaskStoreInterface, tx core.Tx, params *CancelTaskOnWorkerParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	payload, err := json.Marshal(params)
	if err != nil {
		return 0, err
	}

	spec := apigen.TaskSpec{
		Type:    CancelTaskOnWorker,
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	attributes.Timeout = utils.Ptr("5m")
	attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:    "1s",
		MaxAttempts: -1,
	}
	
	
	attributes.Priority = utils.Ptr(int32(2147483647))
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	
	for _, override := range overrides {
		if err := override(task); err != nil {
			return 0, errors.Wrap(err, "failed to apply task override")
		}
	}
	var taskID int32
	if tx == nil {
		taskID, err = taskstore.PushTask(ctx, task)
	} else {
		taskID, err = taskstore.PushTaskWithTx(ctx, tx, task)
	}
	if err != nil {
		return 0, err
	}
	return taskID, nil
}
func (c *Client) RunBroadcastPauseTask(ctx context.Context, params *BroadcastPauseTaskParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runBroadcastPauseTask(ctx, c.taskStore, nil, params, overrides...)
}

func (c *Client) RunBroadcastPauseTaskWithTx(ctx context.Context, tx core.Tx, params *BroadcastPauseTaskParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runBroadcastPauseTask(ctx, c.taskStore, tx, params, overrides...)
}

func (c *Client) runBroadcastPauseTask(ctx context.Context, taskstore taskcore.TaskStoreInterface, tx core.Tx, params *BroadcastPauseTaskParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	payload, err := json.Marshal(params)
	if err != nil {
		return 0, err
	}

	spec := apigen.TaskSpec{
		Type:    BroadcastPauseTask,
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	attributes.Timeout = utils.Ptr("5m")
	attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:    "2s",
		MaxAttempts: -1,
	}
	
	
	attributes.Priority = utils.Ptr(int32(2147483647))
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	
	for _, override := range overrides {
		if err := override(task); err != nil {
			return 0, errors.Wrap(err, "failed to apply task override")
		}
	}
	var taskID int32
	if tx == nil {
		taskID, err = taskstore.PushTask(ctx, task)
	} else {
		taskID, err = taskstore.PushTaskWithTx(ctx, tx, task)
	}
	if err != nil {
		return 0, err
	}
	return taskID, nil
}
func (c *Client) RunPauseTaskOnWorker(ctx context.Context, params *PauseTaskOnWorkerParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runPauseTaskOnWorker(ctx, c.taskStore, nil, params, overrides...)
}

func (c *Client) RunPauseTaskOnWorkerWithTx(ctx context.Context, tx core.Tx, params *PauseTaskOnWorkerParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runPauseTaskOnWorker(ctx, c.taskStore, tx, params, overrides...)
}

func (c *Client) runPauseTaskOnWorker(ctx context.Context, taskstore taskcore.TaskStoreInterface, tx core.Tx, params *PauseTaskOnWorkerParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	payload, err := json.Marshal(params)
	if err != nil {
		return 0, err
	}

	spec := apigen.TaskSpec{
		Type:    PauseTaskOnWorker,
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	attributes.Timeout = utils.Ptr("5m")
	attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:    "1s",
		MaxAttempts: -1,
	}
	
	
	attributes.Priority = utils.Ptr(int32(2147483647))
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	
	for _, override := range overrides {
		if err := override(task); err != nil {
			return 0, errors.Wrap(err, "failed to apply task override")
		}
	}
	var taskID int32
	if tx == nil {
		taskID, err = taskstore.PushTask(ctx, task)
	} else {
		taskID, err = taskstore.PushTaskWithTx(ctx, tx, task)
	}
	if err != nil {
		return 0, err
	}
	return taskID, nil
}
func (c *Client) RunStressProbe(ctx context.Context, params *StressProbeParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runStressProbe(ctx, c.taskStore, nil, params, overrides...)
}

func (c *Client) RunStressProbeWithTx(ctx context.Context, tx core.Tx, params *StressProbeParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runStressProbe(ctx, c.taskStore, tx, params, overrides...)
}

func (c *Client) runStressProbe(ctx context.Context, taskstore taskcore.TaskStoreInterface, tx core.Tx, params *StressProbeParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	payload, err := json.Marshal(params)
	if err != nil {
		return 0, err
	}

	spec := apigen.TaskSpec{
		Type:    StressProbe,
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	attributes.Timeout = utils.Ptr("30s")
	attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:    "1s",
		MaxAttempts: 1,
	}
	
	
	
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	
	for _, override := range overrides {
		if err := override(task); err != nil {
			return 0, errors.Wrap(err, "failed to apply task override")
		}
	}
	var taskID int32
	if tx == nil {
		taskID, err = taskstore.PushTask(ctx, task)
	} else {
		taskID, err = taskstore.PushTaskWithTx(ctx, tx, task)
	}
	if err != nil {
		return 0, err
	}
	return taskID, nil
}
func (c *Client) RunCancelObservableProbe(ctx context.Context, params *CancelObservableProbeParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runCancelObservableProbe(ctx, c.taskStore, nil, params, overrides...)
}

func (c *Client) RunCancelObservableProbeWithTx(ctx context.Context, tx core.Tx, params *CancelObservableProbeParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	return c.runCancelObservableProbe(ctx, c.taskStore, tx, params, overrides...)
}

func (c *Client) runCancelObservableProbe(ctx context.Context, taskstore taskcore.TaskStoreInterface, tx core.Tx, params *CancelObservableProbeParameters, overrides ...taskcore.TaskOverride) (int32, error) {
	payload, err := json.Marshal(params)
	if err != nil {
		return 0, err
	}

	spec := apigen.TaskSpec{
		Type:    CancelObservableProbe,
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	attributes.Timeout = utils.Ptr("30m")
	attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:    "1s",
		MaxAttempts: 1,
	}
	
	
	
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	
	for _, override := range overrides {
		if err := override(task); err != nil {
			return 0, errors.Wrap(err, "failed to apply task override")
		}
	}
	var taskID int32
	if tx == nil {
		taskID, err = taskstore.PushTask(ctx, task)
	} else {
		taskID, err = taskstore.PushTaskWithTx(ctx, tx, task)
	}
	if err != nil {
		return 0, err
	}
	return taskID, nil
}


type DeleteOpaqueKeyParameters struct { 
    // The ID of the opaque key to delete
	KeyID int64 `json:"keyID" yaml:"keyID"`
}

type UpdateWorkerRuntimeConfigParameters struct { 
    // Default weight for unlabeled task group
	DefaultWeight *int32 `json:"defaultWeight" yaml:"defaultWeight"`

    // Label names for weighted groups
	Labels []string `json:"labels" yaml:"labels"`

    // Ack listen timeout window for one iteration
	ListenTimeout *string `json:"listenTimeout" yaml:"listenTimeout"`

    // Maximum percentage of strict-priority slots (0-100)
	MaxStrictPercentage *int32 `json:"maxStrictPercentage" yaml:"maxStrictPercentage"`

    // Fallback retry interval when ack listening is unavailable
	NotifyInterval *string `json:"notifyInterval" yaml:"notifyInterval"`

    // Correlation ID for notify and ack messages
	RequestID *string `json:"requestID" yaml:"requestID"`

    // Weights for labels by index
	Weights []int32 `json:"weights" yaml:"weights"`
}

type InterruptTaskParameters struct { 
    // Ack listen timeout window for one iteration
	ListenTimeout *string `json:"listenTimeout" yaml:"listenTimeout"`

    // Fallback retry interval when ack listening is unavailable
	NotifyInterval *string `json:"notifyInterval" yaml:"notifyInterval"`

    // Correlation ID for notify and ack messages
	RequestID *string `json:"requestID" yaml:"requestID"`

    // Task IDs to interrupt
	TaskIDs []int32 `json:"taskIDs" yaml:"taskIDs"`
}

type BroadcastUpdateWorkerRuntimeConfigParameters struct { 
    // Poll interval used while waiting for worker convergence
	AckPollInterval *string `json:"ackPollInterval" yaml:"ackPollInterval"`

    // Default weight for unlabeled task group
	DefaultWeight *int32 `json:"defaultWeight" yaml:"defaultWeight"`

    // Label names for weighted groups
	Labels []string `json:"labels" yaml:"labels"`

    // Maximum percentage of strict-priority slots (0-100)
	MaxStrictPercentage *int32 `json:"maxStrictPercentage" yaml:"maxStrictPercentage"`

    // Correlation ID for this broadcast command
	RequestID *string `json:"requestID" yaml:"requestID"`

    // Weights for labels by index
	Weights []int32 `json:"weights" yaml:"weights"`

    // Fixed snapshot of worker IDs targeted by this broadcast request
	WorkerIDs []uuid.UUID `json:"workerIDs" yaml:"workerIDs"`
}

type ApplyWorkerRuntimeConfigToWorkerParameters struct { 
    // Correlation ID of the parent broadcast command
	RequestID *string `json:"requestID" yaml:"requestID"`

    // Runtime config version to apply
	Version int64 `json:"version" yaml:"version"`

    // Target worker ID
	WorkerID uuid.UUID `json:"workerID" yaml:"workerID"`
}

type BroadcastCancelTaskParameters struct { 
    // Poll interval used while waiting worker ack tasks
	AckPollInterval *string `json:"ackPollInterval" yaml:"ackPollInterval"`

    // Correlation ID for this broadcast command
	RequestID *string `json:"requestID" yaml:"requestID"`

    // Task IDs to interrupt on each target worker
	TaskIDs []int32 `json:"taskIDs" yaml:"taskIDs"`

    // Fixed snapshot of worker IDs targeted by this broadcast request
	WorkerIDs []uuid.UUID `json:"workerIDs" yaml:"workerIDs"`
}

type CancelTaskOnWorkerParameters struct { 
    // Correlation ID of the parent broadcast command
	RequestID *string `json:"requestID" yaml:"requestID"`

    // Task IDs to interrupt on the target worker
	TaskIDs []int32 `json:"taskIDs" yaml:"taskIDs"`

    // Target worker ID
	WorkerID uuid.UUID `json:"workerID" yaml:"workerID"`
}

type BroadcastPauseTaskParameters struct { 
    // Poll interval used while waiting worker ack tasks
	AckPollInterval *string `json:"ackPollInterval" yaml:"ackPollInterval"`

    // Correlation ID for this broadcast command
	RequestID *string `json:"requestID" yaml:"requestID"`

    // Task IDs to interrupt on each target worker
	TaskIDs []int32 `json:"taskIDs" yaml:"taskIDs"`

    // Fixed snapshot of worker IDs targeted by this broadcast request
	WorkerIDs []uuid.UUID `json:"workerIDs" yaml:"workerIDs"`
}

type PauseTaskOnWorkerParameters struct { 
    // Correlation ID of the parent broadcast command
	RequestID *string `json:"requestID" yaml:"requestID"`

    // Task IDs to interrupt on the target worker
	TaskIDs []int32 `json:"taskIDs" yaml:"taskIDs"`

    // Target worker ID
	WorkerID uuid.UUID `json:"workerID" yaml:"workerID"`
}

type StressProbeParameters struct { 
    // Optional failure mode for chaos tests. Set to "always" to return a retryable error every run.
	FailMode *string `json:"failMode" yaml:"failMode"`

    // Logical group name for test-side metrics and labels
	Group string `json:"group" yaml:"group"`

    // Logical task id for stress-run metrics correlation
	JobID int64 `json:"jobID" yaml:"jobID"`

    // Optional signal service base URL used by running tasks to emit observable heartbeats
	SignalBaseURL *string `json:"signalBaseURL" yaml:"signalBaseURL"`

    // Optional interval in milliseconds between signal emissions while the task is running
	SignalIntervalMs *int32 `json:"signalIntervalMs" yaml:"signalIntervalMs"`

    // Simulated task execution time in milliseconds
	SleepMs int32 `json:"sleepMs" yaml:"sleepMs"`
}

type CancelObservableProbeParameters struct { 
    // Logical group name for test-side metrics and labels
	Group string `json:"group" yaml:"group"`

    // Signal service base URL used by the task to emit observable heartbeats
	SignalBaseURL *string `json:"signalBaseURL" yaml:"signalBaseURL"`

    // Interval in milliseconds between signal emissions while the task is running
	SignalIntervalMs *int32 `json:"signalIntervalMs" yaml:"signalIntervalMs"`
}

func (r *DeleteOpaqueKeyParameters) Parse(spec json.RawMessage) error {
	return json.Unmarshal(spec, r)
}

func (r *DeleteOpaqueKeyParameters) Marshal() (json.RawMessage, error) {
	return json.Marshal(r)
}

func (r *UpdateWorkerRuntimeConfigParameters) Parse(spec json.RawMessage) error {
	return json.Unmarshal(spec, r)
}

func (r *UpdateWorkerRuntimeConfigParameters) Marshal() (json.RawMessage, error) {
	return json.Marshal(r)
}

func (r *InterruptTaskParameters) Parse(spec json.RawMessage) error {
	return json.Unmarshal(spec, r)
}

func (r *InterruptTaskParameters) Marshal() (json.RawMessage, error) {
	return json.Marshal(r)
}

func (r *BroadcastUpdateWorkerRuntimeConfigParameters) Parse(spec json.RawMessage) error {
	return json.Unmarshal(spec, r)
}

func (r *BroadcastUpdateWorkerRuntimeConfigParameters) Marshal() (json.RawMessage, error) {
	return json.Marshal(r)
}

func (r *ApplyWorkerRuntimeConfigToWorkerParameters) Parse(spec json.RawMessage) error {
	return json.Unmarshal(spec, r)
}

func (r *ApplyWorkerRuntimeConfigToWorkerParameters) Marshal() (json.RawMessage, error) {
	return json.Marshal(r)
}

func (r *BroadcastCancelTaskParameters) Parse(spec json.RawMessage) error {
	return json.Unmarshal(spec, r)
}

func (r *BroadcastCancelTaskParameters) Marshal() (json.RawMessage, error) {
	return json.Marshal(r)
}

func (r *CancelTaskOnWorkerParameters) Parse(spec json.RawMessage) error {
	return json.Unmarshal(spec, r)
}

func (r *CancelTaskOnWorkerParameters) Marshal() (json.RawMessage, error) {
	return json.Marshal(r)
}

func (r *BroadcastPauseTaskParameters) Parse(spec json.RawMessage) error {
	return json.Unmarshal(spec, r)
}

func (r *BroadcastPauseTaskParameters) Marshal() (json.RawMessage, error) {
	return json.Marshal(r)
}

func (r *PauseTaskOnWorkerParameters) Parse(spec json.RawMessage) error {
	return json.Unmarshal(spec, r)
}

func (r *PauseTaskOnWorkerParameters) Marshal() (json.RawMessage, error) {
	return json.Marshal(r)
}

func (r *StressProbeParameters) Parse(spec json.RawMessage) error {
	return json.Unmarshal(spec, r)
}

func (r *StressProbeParameters) Marshal() (json.RawMessage, error) {
	return json.Marshal(r)
}

func (r *CancelObservableProbeParameters) Parse(spec json.RawMessage) error {
	return json.Unmarshal(spec, r)
}

func (r *CancelObservableProbeParameters) Marshal() (json.RawMessage, error) {
	return json.Marshal(r)
}


type ExecutorInterface interface { 
     // Delete an opaque key
	ExecuteDeleteOpaqueKey(ctx context.Context, task worker.Task, params *DeleteOpaqueKeyParameters) error
 
	// Hook called when deleteOpaqueKey fails
	OnDeleteOpaqueKeyFailed(ctx context.Context, taskID int32, params *DeleteOpaqueKeyParameters, tx core.Tx) error

     // Update worker runtime config and wait for alive workers to apply it
	ExecuteUpdateWorkerRuntimeConfig(ctx context.Context, task worker.Task, params *UpdateWorkerRuntimeConfigParameters) error
 

     // Interrupt a task and stop any in-flight execution
	ExecuteInterruptTask(ctx context.Context, task worker.Task, params *InterruptTaskParameters) error
 

     // Broadcast a runtime config update command to all alive workers
	ExecuteBroadcastUpdateWorkerRuntimeConfig(ctx context.Context, task worker.Task, params *BroadcastUpdateWorkerRuntimeConfigParameters) error
 

     // Apply a runtime config version on one specific worker
	ExecuteApplyWorkerRuntimeConfigToWorker(ctx context.Context, task worker.Task, params *ApplyWorkerRuntimeConfigToWorkerParameters) error
 

     // Broadcast cancel-task command to alive workers
	ExecuteBroadcastCancelTask(ctx context.Context, task worker.Task, params *BroadcastCancelTaskParameters) error
 

     // Cancel in-flight task execution on one specific worker
	ExecuteCancelTaskOnWorker(ctx context.Context, task worker.Task, params *CancelTaskOnWorkerParameters) error
 

     // Broadcast pause-task command to alive workers
	ExecuteBroadcastPauseTask(ctx context.Context, task worker.Task, params *BroadcastPauseTaskParameters) error
 

     // Pause in-flight task execution on one specific worker
	ExecutePauseTaskOnWorker(ctx context.Context, task worker.Task, params *PauseTaskOnWorkerParameters) error
 

     // No-op stress probe task for worker E2E benchmarking
	ExecuteStressProbe(ctx context.Context, task worker.Task, params *StressProbeParameters) error
 

     // Long-running observable task used to validate cancellation semantics under chaos
	ExecuteCancelObservableProbe(ctx context.Context, task worker.Task, params *CancelObservableProbeParameters) error
 
}

type TaskHandler struct {
	executor ExecutorInterface

	externalTaskHandler []worker.TaskHandler
}

func NewTaskHandler(executor ExecutorInterface) worker.TaskHandler {
	return &TaskHandler{
		executor: executor,
	}
}

func (f *TaskHandler) RegisterTaskHandler(handler worker.TaskHandler) {
	f.externalTaskHandler = append(f.externalTaskHandler, handler)
}

func (f *TaskHandler) HandleTask(ctx context.Context, task worker.Task) error {
	for _, handler := range f.externalTaskHandler {
		if err := handler.HandleTask(ctx, task); err != nil {
			if errors.Is(err, worker.ErrUnknownTaskType) {
				continue
			}
			return err
		}
		return nil
	}

	switch task.GetType() { 
	case DeleteOpaqueKey:
		var params DeleteOpaqueKeyParameters
		if err := json.Unmarshal(task.GetPayload(), &params); err != nil {
			return fmt.Errorf("failed to parse deleteOpaqueKey parameters: %w", err)
		}
		return f.executor.ExecuteDeleteOpaqueKey(ctx, task, &params)
		
	case UpdateWorkerRuntimeConfig:
		var params UpdateWorkerRuntimeConfigParameters
		if err := json.Unmarshal(task.GetPayload(), &params); err != nil {
			return fmt.Errorf("failed to parse updateWorkerRuntimeConfig parameters: %w", err)
		}
		return f.executor.ExecuteUpdateWorkerRuntimeConfig(ctx, task, &params)
		
	case InterruptTask:
		var params InterruptTaskParameters
		if err := json.Unmarshal(task.GetPayload(), &params); err != nil {
			return fmt.Errorf("failed to parse interruptTask parameters: %w", err)
		}
		return f.executor.ExecuteInterruptTask(ctx, task, &params)
		
	case BroadcastUpdateWorkerRuntimeConfig:
		var params BroadcastUpdateWorkerRuntimeConfigParameters
		if err := json.Unmarshal(task.GetPayload(), &params); err != nil {
			return fmt.Errorf("failed to parse broadcastUpdateWorkerRuntimeConfig parameters: %w", err)
		}
		return f.executor.ExecuteBroadcastUpdateWorkerRuntimeConfig(ctx, task, &params)
		
	case ApplyWorkerRuntimeConfigToWorker:
		var params ApplyWorkerRuntimeConfigToWorkerParameters
		if err := json.Unmarshal(task.GetPayload(), &params); err != nil {
			return fmt.Errorf("failed to parse applyWorkerRuntimeConfigToWorker parameters: %w", err)
		}
		return f.executor.ExecuteApplyWorkerRuntimeConfigToWorker(ctx, task, &params)
		
	case BroadcastCancelTask:
		var params BroadcastCancelTaskParameters
		if err := json.Unmarshal(task.GetPayload(), &params); err != nil {
			return fmt.Errorf("failed to parse broadcastCancelTask parameters: %w", err)
		}
		return f.executor.ExecuteBroadcastCancelTask(ctx, task, &params)
		
	case CancelTaskOnWorker:
		var params CancelTaskOnWorkerParameters
		if err := json.Unmarshal(task.GetPayload(), &params); err != nil {
			return fmt.Errorf("failed to parse cancelTaskOnWorker parameters: %w", err)
		}
		return f.executor.ExecuteCancelTaskOnWorker(ctx, task, &params)
		
	case BroadcastPauseTask:
		var params BroadcastPauseTaskParameters
		if err := json.Unmarshal(task.GetPayload(), &params); err != nil {
			return fmt.Errorf("failed to parse broadcastPauseTask parameters: %w", err)
		}
		return f.executor.ExecuteBroadcastPauseTask(ctx, task, &params)
		
	case PauseTaskOnWorker:
		var params PauseTaskOnWorkerParameters
		if err := json.Unmarshal(task.GetPayload(), &params); err != nil {
			return fmt.Errorf("failed to parse pauseTaskOnWorker parameters: %w", err)
		}
		return f.executor.ExecutePauseTaskOnWorker(ctx, task, &params)
		
	case StressProbe:
		var params StressProbeParameters
		if err := json.Unmarshal(task.GetPayload(), &params); err != nil {
			return fmt.Errorf("failed to parse stressProbe parameters: %w", err)
		}
		return f.executor.ExecuteStressProbe(ctx, task, &params)
		
	case CancelObservableProbe:
		var params CancelObservableProbeParameters
		if err := json.Unmarshal(task.GetPayload(), &params); err != nil {
			return fmt.Errorf("failed to parse cancelObservableProbe parameters: %w", err)
		}
		return f.executor.ExecuteCancelObservableProbe(ctx, task, &params)
		
	default:
		return errors.Wrapf(worker.ErrUnknownTaskType, "unknown task type: %s", task.GetType())
	}
}

func (f *TaskHandler) OnTaskFailed(ctx context.Context, tx core.Tx, failedTaskSpec worker.TaskSpec, taskID int32) error {
	for _, handler := range f.externalTaskHandler {
		if err := handler.OnTaskFailed(ctx, tx, failedTaskSpec, taskID); err != nil {
			if errors.Is(err, worker.ErrUnknownTaskType) {
				continue
			}
			return err
		}
		return nil
	}

	// Call the appropriate OnXXXFailed hook method
	switch failedTaskSpec.GetType() { 
	case DeleteOpaqueKey:
		var params DeleteOpaqueKeyParameters
		if err := json.Unmarshal(failedTaskSpec.GetPayload(), &params); err != nil {
			return fmt.Errorf("failed to parse deleteOpaqueKey parameters: %w", err)
		}
		return f.executor.OnDeleteOpaqueKeyFailed(ctx, taskID, &params, tx)
	default:
		return nil // No hook configured for this task type
	}
}
