BEGIN;

CREATE TABLE IF NOT EXISTS anclax.fsm (
    id    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    type  VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
