// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package querier

import (
	"time"

	"github.com/cloudcarver/anchor/pkg/apigen"
)

type AccessKeyPair struct {
	AccessKey string
	SecretKey string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type AccessRule struct {
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Event struct {
	ID        int32
	Spec      apigen.EventSpec
	CreatedAt time.Time
}

type OpaqueKey struct {
	ID        int64
	Key       []byte
	UserID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Org struct {
	ID        int32
	Name      string
	Tz        string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OrgOwner struct {
	OrgID     int32
	UserID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OrgUser struct {
	OrgID     int32
	UserID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Role struct {
	ID          int32
	OrgID       int32
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type RoleAccessRule struct {
	RoleID         int32
	AccessRuleName string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Task struct {
	ID         int32
	Attributes apigen.TaskAttributes
	Spec       apigen.TaskSpec
	Status     string
	StartedAt  *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type User struct {
	ID           int32
	Name         string
	PasswordHash string
	PasswordSalt string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UsersRole struct {
	UserID    int32
	RoleID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
