// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package querier

import (
	"time"

	"github.com/google/uuid"
)

type Key struct {
	ID         uuid.UUID
	PublicKey  string
	PrivateKey string
	ExpiredAt  time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type OrgSetting struct {
	OrganizationID int32
	Timezone       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Organization struct {
	ID        int32
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OrganizationOwner struct {
	UserID         int32
	OrganizationID int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type RefreshToken struct {
	Token     string
	ExpiredAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID             int32
	Name           string
	PasswordHash   string
	PasswordSalt   string
	OrganizationID int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
