// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package querier

import (
	"context"

	"github.com/cloudcarver/anchor/internal/apigen"
)

type Querier interface {
	CreateKeyPair(ctx context.Context, arg CreateKeyPairParams) (*AccessKeyPair, error)
	CreateOpaqueKey(ctx context.Context, arg CreateOpaqueKeyParams) (int64, error)
	CreateOrg(ctx context.Context, name string) (*Org, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (*Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeleteKeyPair(ctx context.Context, accessKey string) error
	DeleteOpaqueKey(ctx context.Context, id int64) error
	DeleteOpaqueKeys(ctx context.Context, userID int32) error
	DeleteUserByName(ctx context.Context, name string) error
	GetKeyPair(ctx context.Context, accessKey string) (*AccessKeyPair, error)
	GetOpaqueKey(ctx context.Context, id int64) ([]byte, error)
	GetOrg(ctx context.Context, id int32) (*Org, error)
	GetOrgByName(ctx context.Context, name string) (*Org, error)
	GetTaskByID(ctx context.Context, id int32) (*Task, error)
	GetUser(ctx context.Context, id int32) (*User, error)
	GetUserByName(ctx context.Context, name string) (*User, error)
	InsertEvent(ctx context.Context, spec apigen.EventSpec) (*Event, error)
	InsertOrgOwner(ctx context.Context, arg InsertOrgOwnerParams) (*OrgOwner, error)
	InsertOrgUser(ctx context.Context, arg InsertOrgUserParams) (*OrgUser, error)
	PullTask(ctx context.Context) (*Task, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) error
	UpdateTaskStartedAt(ctx context.Context, arg UpdateTaskStartedAtParams) error
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error
}

var _ Querier = (*Queries)(nil)
