// This file is generated by tools, DO NOT EDIT.
package runner

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/cloudcarver/anchor/internal/apigen"
	"github.com/cloudcarver/anchor/internal/model"
	"github.com/cloudcarver/anchor/internal/task"
	"github.com/cloudcarver/anchor/internal/task/worker"
	"github.com/cloudcarver/anchor/internal/utils"
)

func init() {
	utils.Noop()
}

const ( 
	DeleteOpaqueKey = "deleteOpaqueKey" 
)

type TaskRunner interface { 
    // Delete an opaque key
	DeleteOpaqueKey(ctx *model.Context, params *DeleteOpaqueKeyParameters) error
}

type Client struct {
	taskStore task.TaskStoreInterface
	now       func() time.Time
}

func NewTaskRunner(taskStore task.TaskStoreInterface) TaskRunner {
	return &Client{
		taskStore: taskStore,
	}
}


func (c *Client) DeleteOpaqueKey(ctx *model.Context, params *DeleteOpaqueKeyParameters) error {
	payload, err := params.Marshal()
	if err != nil {
		return err
	}

	spec := apigen.TaskSpec{
		Type:    DeleteOpaqueKey,
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	
	attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:             "30m",
		AlwaysRetryOnFailure: true,
	}
	
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	
	if _, err := c.taskStore.PushTask(ctx, task); err != nil {
		return err
	}
	return nil
}


type DeleteOpaqueKeyParameters struct { 
    // The ID of the opaque key to delete
	KeyID int64 `json:"keyID" yaml:"keyID"`
}

func (r *DeleteOpaqueKeyParameters) Parse(spec json.RawMessage) error {
	return json.Unmarshal(spec, r)
}

func (r *DeleteOpaqueKeyParameters) Marshal() (json.RawMessage, error) {
	return json.Marshal(r)
}

type ExecutorInterface interface { 
    // Delete an opaque key
	DeleteOpaqueKey(params *DeleteOpaqueKeyParameters) error
}

type TaskHandler struct {
	executor ExecutorInterface
}

func NewTaskHandler(executor ExecutorInterface) worker.TaskHandler {
	return &TaskHandler{
		executor: executor,
	}
}

func (f *TaskHandler) HandleTask(c *model.Context, spec *apigen.TaskSpec) error {
	switch spec.Type { 
	case DeleteOpaqueKey:
		var params DeleteOpaqueKeyParameters
		if err := params.Parse(spec.Payload); err != nil {
			return fmt.Errorf("failed to parse deleteOpaqueKey parameters: %w", err)
		}
		return f.executor.DeleteOpaqueKey(&params)
		
	default:
		return fmt.Errorf("unknown handler %s", spec.Type)
	}
}
