// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/hooks/hooks.go
//
// Generated by this command:
//
//	mockgen -source pkg/hooks/hooks.go -destination pkg/hooks/mock_gen.go -package hooks
//

// Package hooks is a generated GoMock package.
package hooks

import (
	context "context"
	reflect "reflect"

	macaroons "github.com/cloudcarver/anchor/pkg/macaroons"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockAnchorHookInterface is a mock of AnchorHookInterface interface.
type MockAnchorHookInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAnchorHookInterfaceMockRecorder
	isgomock struct{}
}

// MockAnchorHookInterfaceMockRecorder is the mock recorder for MockAnchorHookInterface.
type MockAnchorHookInterfaceMockRecorder struct {
	mock *MockAnchorHookInterface
}

// NewMockAnchorHookInterface creates a new mock instance.
func NewMockAnchorHookInterface(ctrl *gomock.Controller) *MockAnchorHookInterface {
	mock := &MockAnchorHookInterface{ctrl: ctrl}
	mock.recorder = &MockAnchorHookInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnchorHookInterface) EXPECT() *MockAnchorHookInterfaceMockRecorder {
	return m.recorder
}

// OnCreateToken mocks base method.
func (m *MockAnchorHookInterface) OnCreateToken(ctx context.Context, userID int32, macaroon *macaroons.Macaroon) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnCreateToken", ctx, userID, macaroon)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnCreateToken indicates an expected call of OnCreateToken.
func (mr *MockAnchorHookInterfaceMockRecorder) OnCreateToken(ctx, userID, macaroon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnCreateToken", reflect.TypeOf((*MockAnchorHookInterface)(nil).OnCreateToken), ctx, userID, macaroon)
}

// OnOrgCreatedWithTx mocks base method.
func (m *MockAnchorHookInterface) OnOrgCreatedWithTx(ctx context.Context, tx pgx.Tx, orgID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnOrgCreatedWithTx", ctx, tx, orgID)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnOrgCreatedWithTx indicates an expected call of OnOrgCreatedWithTx.
func (mr *MockAnchorHookInterfaceMockRecorder) OnOrgCreatedWithTx(ctx, tx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnOrgCreatedWithTx", reflect.TypeOf((*MockAnchorHookInterface)(nil).OnOrgCreatedWithTx), ctx, tx, orgID)
}

// OnUserCreatedWithTx mocks base method.
func (m *MockAnchorHookInterface) OnUserCreatedWithTx(ctx context.Context, tx pgx.Tx, userID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnUserCreatedWithTx", ctx, tx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnUserCreatedWithTx indicates an expected call of OnUserCreatedWithTx.
func (mr *MockAnchorHookInterfaceMockRecorder) OnUserCreatedWithTx(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnUserCreatedWithTx", reflect.TypeOf((*MockAnchorHookInterface)(nil).OnUserCreatedWithTx), ctx, tx, userID)
}

// RegisterOnCreateToken mocks base method.
func (m *MockAnchorHookInterface) RegisterOnCreateToken(hook OnCreateToken) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterOnCreateToken", hook)
}

// RegisterOnCreateToken indicates an expected call of RegisterOnCreateToken.
func (mr *MockAnchorHookInterfaceMockRecorder) RegisterOnCreateToken(hook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterOnCreateToken", reflect.TypeOf((*MockAnchorHookInterface)(nil).RegisterOnCreateToken), hook)
}

// RegisterOnOrgCreatedWithTx mocks base method.
func (m *MockAnchorHookInterface) RegisterOnOrgCreatedWithTx(hook OnOrgCreatedWithTx) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterOnOrgCreatedWithTx", hook)
}

// RegisterOnOrgCreatedWithTx indicates an expected call of RegisterOnOrgCreatedWithTx.
func (mr *MockAnchorHookInterfaceMockRecorder) RegisterOnOrgCreatedWithTx(hook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterOnOrgCreatedWithTx", reflect.TypeOf((*MockAnchorHookInterface)(nil).RegisterOnOrgCreatedWithTx), hook)
}

// RegisterOnUserCreatedWithTx mocks base method.
func (m *MockAnchorHookInterface) RegisterOnUserCreatedWithTx(hook OnUserCreatedWithTx) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterOnUserCreatedWithTx", hook)
}

// RegisterOnUserCreatedWithTx indicates an expected call of RegisterOnUserCreatedWithTx.
func (mr *MockAnchorHookInterfaceMockRecorder) RegisterOnUserCreatedWithTx(hook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterOnUserCreatedWithTx", reflect.TypeOf((*MockAnchorHookInterface)(nil).RegisterOnUserCreatedWithTx), hook)
}
