// This file is generated by tools, DO NOT EDIT.
package task

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/cloudcarver/anchor/pkg/apigen"
	"github.com/cloudcarver/anchor/pkg/model"
	"github.com/cloudcarver/anchor/pkg/task"
	"github.com/cloudcarver/anchor/pkg/task/worker"
	"github.com/cloudcarver/anchor/pkg/utils"
	"github.com/pkg/errors"
)

func init() {
	utils.Noop()
}

const ( 
	IncrementCounter = "incrementCounter" 
)

type TaskRunner interface { 
    // Increment the counter
	IncrementCounter(ctx *model.Context, params *IncrementCounterParameters) error
}

type Client struct {
	taskStore task.TaskStoreInterface
	now       func() time.Time
}

func NewTaskRunner(taskStore task.TaskStoreInterface) TaskRunner {
	return &Client{
		taskStore: taskStore,
		now:       time.Now,
	}
}


func (c *Client) IncrementCounter(ctx *model.Context, params *IncrementCounterParameters) error {
	payload, err := params.Marshal()
	if err != nil {
		return err
	}

	spec := apigen.TaskSpec{
		Type:    IncrementCounter,
		Payload: payload,
	}
	attributes := apigen.TaskAttributes{}
	
	attributes.RetryPolicy = &apigen.TaskRetryPolicy{
		Interval:             "30m",
		AlwaysRetryOnFailure: true,
	}
	attributes.Cronjob = &apigen.TaskCronjob{
		CronExpression: "0 10 * * *",
	}
	task := &apigen.Task{
		Attributes: attributes,
		Spec:       spec,
		Status:     apigen.Pending,
	}
	
	if _, err := c.taskStore.PushTask(ctx, task); err != nil {
		return err
	}
	return nil
}


type IncrementCounterParameters struct { 
    // 
	Amount *int32 `json:"amount" yaml:"amount"`
}

func (r *IncrementCounterParameters) Parse(spec json.RawMessage) error {
	return json.Unmarshal(spec, r)
}

func (r *IncrementCounterParameters) Marshal() (json.RawMessage, error) {
	return json.Marshal(r)
}

type ExecutorInterface interface { 
    // Increment the counter
	IncrementCounter(ctx context.Context, params *IncrementCounterParameters) error
}

type TaskHandler struct {
	executor ExecutorInterface

	externalTaskHandler []worker.TaskHandler
}

func NewTaskHandler(executor ExecutorInterface) worker.TaskHandler {
	return &TaskHandler{
		executor: executor,
	}
}

func (f *TaskHandler) RegisterTaskHandler(handler worker.TaskHandler) {
	f.externalTaskHandler = append(f.externalTaskHandler, handler)
}

func (f *TaskHandler) HandleTask(c *model.Context, spec worker.TaskSpec) error {
	for _, handler := range f.externalTaskHandler {
		if err := handler.HandleTask(c, spec); err != nil {
			if errors.Is(err, worker.ErrUnknownTaskType) {
				continue
			}
			return err
		}
		return nil
	}

	switch spec.GetType() { 
	case IncrementCounter:
		var params IncrementCounterParameters
		if err := params.Parse(spec.GetPayload()); err != nil {
			return fmt.Errorf("failed to parse incrementCounter parameters: %w", err)
		}
		return f.executor.IncrementCounter(c.Context, &params)
		
	default:
		return fmt.Errorf("unknown handler %s", spec.GetType())
	}
}
