// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/cloudcarver/anchor/internal/apps/server"
	"github.com/cloudcarver/anchor/internal/auth"
	"github.com/cloudcarver/anchor/internal/config"
	"github.com/cloudcarver/anchor/internal/controller"
	"github.com/cloudcarver/anchor/internal/model"
	"github.com/cloudcarver/anchor/internal/service"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	modelInterface, err := model.NewModel(configConfig)
	if err != nil {
		return nil, err
	}
	authStoreInterface, err := auth.NewAuthStore(modelInterface, configConfig)
	if err != nil {
		return nil, err
	}
	authInterface, err := auth.NewAuth(configConfig, authStoreInterface, modelInterface)
	if err != nil {
		return nil, err
	}
	serviceInterface := service.NewService(configConfig, modelInterface, authInterface)
	controllerController := controller.NewController(serviceInterface, authInterface)
	serverServer, err := server.NewServer(configConfig, controllerController, authInterface)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
