services:
  dev:
    build:
      context: .
      dockerfile: ./dev/Dockerfile.dev
    ports:
      - "2910:2910"
    command:
    - go
    - run
    - ./cmd
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYAPP_ANCLAX_HOST: 0.0.0.0
      MYAPP_ANCLAX_PORT: 2910
      MYAPP_ANCLAX_PG_HOST: db
      MYAPP_ANCLAX_PG_PORT: 5432
      MYAPP_ANCLAX_PG_USER: postgres
      MYAPP_ANCLAX_PG_PASSWORD: "${POSTGRES_PASSWORD:?Run sh dev/setup.sh to create .env}"
      MYAPP_ANCLAX_PG_DB: postgres
      MYAPP_ANCLAX_PG_SSLMODE: disable
    volumes:
      - ./:/app
      - go-data:/go/pkg/mod
      - go-build-data:/root/.cache/go-build

  db:
    image: "postgres:17-bookworm"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:?Run sh dev/setup.sh to create .env}"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  db-data:
  go-data:
  go-build-data:
